export const SubCategorias = [
  { code: "accesoriosDeBaños", nombre: "Accesorios de baños" },
  { code: "accesoriosDePisosDeVinyl", nombre: "Accesorios de pisos de vinyl" },
  {
    code: "accesoriosDePisosLaminados",
    nombre: "Accesorios de pisos laminados",
  },
  { code: "accesoriosParaCocinas", nombre: "Accesorios para cocinas" },
  { code: "accesoriosTraslucidas", nombre: "Accesorios traslúcidas" },
  { code: "acm", nombre: "ACM" },
  { code: "alfombras", nombre: "Alfombras" },
  { code: "default", nombre: "Default" },
  { code: "bajoPiso", nombre: "Bajo piso" },
  { code: "cintas", nombre: "Cintas" },
  { code: "clading", nombre: "Clading" },
  { code: "clavos", nombre: "Clavos" },
  { code: "closet", nombre: "Clóset" },
  { code: "construccionHigienica", nombre: "Construcción higiénica" },
  { code: "convolute", nombre: "Convolute" },
  { code: "cornisas", nombre: "Cornisas" },
  { code: "decking", nombre: "Decking" },
  { code: "duchas", nombre: "Duchas" },
  { code: "escaleras", nombre: "Escaleras" },
  { code: "espejos", nombre: "Espejos" },
  { code: "esquineros", nombre: "Esquineros" },
  { code: "estucos", nombre: "Estucos" },
  { code: "fenolico", nombre: "Fenólico" },
  { code: "fregaderos", nombre: "Fregaderos" },
  { code: "frp", nombre: "FRP" },
  { code: "fulminantes", nombre: "Fulminantes" },
  {
    code: "gramasYJardinesSintenticos",
    nombre: "Gramas y jardines sintéticos",
  },
  { code: "guardasillas", nombre: "Guardasillas" },
  { code: "herramientas", nombre: "Herramientas" },
  { code: "impermeabilizante", nombre: "Impermeabilizante" },
  { code: "inodoros", nombre: "Inodoros" },
  { code: "jardineras", nombre: "Jardineras" },
  { code: "lamparaEmpotrable", nombre: "Lámpara empotrable" },
  { code: "lamparaSuperficie", nombre: "Lámpara superficie" },
  { code: "lanaMineral", nombre: "Lana mineral" },
  { code: "lavamanos", nombre: "Lavamanos" },
  { code: "ledPanel", nombre: "LED panel" },
  { code: "lijas", nombre: "Lijas" },
  { code: "louver", nombre: "Louver" },
  { code: "masillasParaSheetrock", nombre: "Masillas para sheetrock" },
  { code: "mesa", nombre: "Mesa" },
  { code: "mezcladorasDeBaños", nombre: "Mezcladoras de baños" },
  { code: "mezcladorasParaFregaderos", nombre: "Mezcladoras para fregaderos" },
  { code: "mortero", nombre: "Mortero" },
  { code: "mueblesDeBaños", nombre: "Muebles de baños" },
  { code: "nobius", nombre: "Nobius" },
  { code: "ojitoBuey", nombre: "Ojito de buey" },
  { code: "panelesDeAcceso", nombre: "Paneles de acceso" },
  { code: "panelPu", nombre: "Panel PU" },
  { code: "pegamentos", nombre: "Pegamentos" },
  {
    code: "pegamentosYSiliconesAsepticos",
    nombre: "Pegamentos y silicones asépticos",
  },
  { code: "perfilesLivianosParaMuros", nombre: "Perfiles livianos para muros" },
  { code: "perfilesPesadosParaMuros", nombre: "Perfiles pesados para muros" },
  { code: "pergolas", nombre: "Pérgolas" },
  { code: "pisoDeGoma", nombre: "Piso de goma" },
  { code: "pisosDeVinyl", nombre: "Pisos de vinyl" },
  { code: "pisosLaminado", nombre: "Pisos laminado" },
  { code: "plafonFibraMineral", nombre: "Plafón de fibra mineral" },
  { code: "plafonPvc", nombre: "Plafón PVC" },
  { code: "planchasAcusticas", nombre: "Planchas acústicas" },
  { code: "planchasDeExterior", nombre: "Planchas de exterior" },
  { code: "planchasDeInterior", nombre: "Planchas de interior" },
  { code: "planchasSound", nombre: "Planchas sound" },
  { code: "planchasTipoMarmol", nombre: "Planchas tipo mármol" },
  { code: "policarbonato", nombre: "Policarbonato" },
  { code: "poliestireno", nombre: "Poliestireno" },
  { code: "puertasPlegables", nombre: "Puertas plegables" },
  { code: "revestimientoPvc", nombre: "Revestimiento PVC" },
  { code: "rollosAluminizados", nombre: "Rollos aluminizados" },
  { code: "siding", nombre: "Siding" },
  { code: "sillas", nombre: "Sillas" },
  { code: "sofa", nombre: "Sofá" },
  { code: "suspensionDePlafones", nombre: "Suspensión de plafones" },
  { code: "taburete", nombre: "Taburete" },
  { code: "tarugos", nombre: "Tarugos" },
  { code: "tipoAluzinc", nombre: "Tipo aluzinc" },
  { code: "topakustik", nombre: "Topakustik" },
  { code: "tornillosAutobarrena", nombre: "Tornillos autobarrenados" },
  { code: "tornillosNeopreno", nombre: "Tornillos neopreno" },
  { code: "tornillosPuntaFina", nombre: "Tornillos punta fina" },
  { code: "tornillosTapper", nombre: "Tornillos tapper" },
  { code: "wpc", nombre: "WPC" },
  { code: "zocalos", nombre: "Zócalos" },
];
