export const CategoriasProductos = [
  { nombre: "Accesorios p/Baños", codigoInterno: "accesoriosPBanos" },
  { nombre: "Accesorrios Fenolico", codigoInterno: "accesorriosFenolico" },
  { nombre: "ACM", codigoInterno: "acm" },
  { nombre: "ACTIVOS FIJOS", codigoInterno: "activosFijos" },
  { nombre: "Aires Acondicionado", codigoInterno: "airesAcondicionado" },
  { nombre: "Aislantes", codigoInterno: "aislantes" },
  { nombre: "ARTICULO DE COMPRA", codigoInterno: "articuloDeCompra" },
  { nombre: "ATT", codigoInterno: "att" },
  { nombre: "Cladding", codigoInterno: "cladding" },
  { nombre: "Closet", codigoInterno: "closet" },
  { nombre: "Cocinas", codigoInterno: "cocinas" },
  { nombre: "Cortinas", codigoInterno: "cortinas" },
  { nombre: "Domotica", codigoInterno: "domotica" },
  { nombre: "Electrico", codigoInterno: "electrico" },
  { nombre: "Escaleras", codigoInterno: "escaleras" },
  { nombre: "Glasliner", codigoInterno: "glasliner" },
  { nombre: "Grama Sintetic/Alfom", codigoInterno: "gramaSinteticAlfom" },
  { nombre: "Grossfilex", codigoInterno: "grossfilex" },
  { nombre: "Impermeabilizante", codigoInterno: "impermeabilizante" },
  { nombre: "INACTIVOS", codigoInterno: "inactivos" },
  { nombre: "Instalacion", codigoInterno: "instalacion" },
  { nombre: "Jardineras y Tarros", codigoInterno: "jardinerasYTarros" },
  { nombre: "Lámparas", codigoInterno: "lamparas" },
  { nombre: "Linea Aseptica", codigoInterno: "lineaAseptica" },
  { nombre: "Macrolux", codigoInterno: "macrolux" },
  { nombre: "Masilla", codigoInterno: "masilla" },
  { nombre: "Material Puertas PVC", codigoInterno: "materialPuertasPvc" },
  { nombre: "MaterialesEspeciales", codigoInterno: "materialesEspeciales" },
  { nombre: "Metales/perfiles", codigoInterno: "metalesPerfiles" },
  { nombre: "Miscelaneos", codigoInterno: "miscelaneos" },
  { nombre: "Mobiliario", codigoInterno: "mobiliario" },
  { nombre: "Mobiliario Grossfile", codigoInterno: "mobiliarioGrossfile" },
  { nombre: "Molduras de foam", codigoInterno: "moldurasDeFoam" },
  {
    nombre: "Paneles y accesorios PVC",
    codigoInterno: "panelesYAccesoriosPvc",
  },
  { nombre: "Pegamentos", codigoInterno: "pegamentos" },
  { nombre: "Pisos", codigoInterno: "pisos" },
  { nombre: "Pistolas/Herramienta", codigoInterno: "pistolasHerramienta" },
  { nombre: "Plafones", codigoInterno: "plafones" },
  { nombre: "PlanchaFenolica/Form", codigoInterno: "planchaFenolicaForm" },
  { nombre: "Planchas", codigoInterno: "planchas" },
  { nombre: "Plycem", codigoInterno: "plycem" },
  { nombre: "poliacryl", codigoInterno: "poliacryl" },
  { nombre: "Porcelanato", codigoInterno: "porcelanato" },
  { nombre: "POSTO Design", codigoInterno: "postoDesign" },
  { nombre: "Prodex", codigoInterno: "prodex" },
  { nombre: "Puertas PVC/OtroMat", codigoInterno: "puertasPvcOtroMat" },
  { nombre: "Suspensión Plafones", codigoInterno: "suspensionPlafones" },
  { nombre: "Suspensión yeso", codigoInterno: "suspensionYeso" },
  { nombre: "Tapa y panel de Acce", codigoInterno: "tapaYPanelDeAcce" },
  { nombre: "Tornillos", codigoInterno: "tornillos" },
];
