export const gruposCorreos = [
  {
    nombre: "Ventas principal",
    code: "ventasPrincipal01",
    correo: "ventasprincipal@cielosacusticos.com",
  },
  {
    nombre: "Sucursal santiago",
    code: "sucSantiago02",
    correo: "santiago@cielosacusticos.com",
  },
  {
    nombre: "Sucursal Zona Oriental",
    code: "sucZonaOriental03",

    correo: "zonaoriental@cielosacusticos.com",
  },
  {
    nombre: "Sucursal Bavaro",
    code: "sucBavaro04",
    correo: "bavaro@cielosacusticos.com",
  },
  {
    nombre: "Proyectos",
    code: "proyectos05",
    correo: "proyectos@cielosacusticos.com",
  },
];
const listaCorreos = [
  {
    nombre: "Alexander Escolastico",
    correo: "Aescolastico@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  { nombre: "Alexandra Medina", correo: "amedina@cielosacusticos.com" },
  {
    nombre: "Elisa Polanco",
    correo: "cajasantiago@cielosacusticos.com",
    grupos: ["sucSantiago02"],
  },
  {
    nombre: "Braulyn Garrido",
    correo: "bgarrido@cielosacusticos.com",
    grupos: ["sucBavaro04", "proyectos05"],
  },
  {
    nombre: "Leidy Ramírez",
    correo: "lramirez@cielosacusticos.com",
    grupos: ["sucBavaro04", "proyectos05"],
  },
  { nombre: "Ana Patricia Jiménez", correo: "pjimenez@cielosacusticos.com" },
  {
    nombre: "Andrea Peláez",
    correo: "apelaez@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  { nombre: "Andreina Rodríguez", correo: "arodriguez@cielosacusticos.com" },
  {
    nombre: "Andry Alcantara",
    correo: "aalcantara@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  {
    nombre: "Angel Eduardo Rodríguez",
    correo: "aerodriguez@cielosacusticos.com",
  },
  { nombre: "Angel Polanco", correo: "apolanco@cielosacusticos.com" },
  { nombre: "Basilia Garcia", correo: "bgarcia@cielosacusticos.com" },
  {
    nombre: "Bernardo Méndez",
    correo: "bmendez@cielosacusticos.com",
    grupos: ["sucSantiago02"],
  },
  {
    nombre: "Camila Hoyos Ramírez",
    correo: "cramirez@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  {
    nombre: "Candy García",
    correo: "cgarcia@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Carlos Hiciano", correo: "chiciano@cielosacusticos.com" },
  { nombre: "Carlos Méndez", correo: "cmendez@cielosacusticos.com" },
  {
    nombre: "Carlos Morales",
    correo: "cmorales@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  {
    nombre: "Carolina Ortiz",
    correo: "cortiz@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Casandra Alcántara", correo: "calcantara@cielosacusticos.com" },
  { nombre: "Christian Solano", correo: "csolano@cielosacusticos.com" },
  { nombre: "Chrysalis Cabrera", correo: "ccabrera@cielosacusticos.com" },
  {
    nombre: "CINDY ROSARIO",
    correo: "crosario@cielosacusticos.com",
    grupos: ["sucBavaro04", "proyectos05"],
  },
  { nombre: "Cinthia Diaz", correo: "cdiaz@cielosacusticos.com" },
  {
    nombre: "Claudia Flech",
    correo: "cflech@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  { nombre: "Claudia Hernández", correo: "chernandez@cielosacusticos.com" },
  { nombre: "Clorycel Almonte", correo: "calmonte@cielosacusticos.com" },
  {
    nombre: "Contabilidad PyL",
    correo: "contabilidadpyl@cielosacusticossrl.onmicrosoft.com",
  },
  {
    nombre: "Daniela Jaquez",
    correo: "djaquez@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "Daniela Perez",
    correo: "cajabavaro@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  {
    nombre: "Danyris Martínez Gutiérrez",
    correo: "dgutierrez@cielosacusticos.com",
    grupos: ["proyectos05", "sucBavaro04"],
  },
  { nombre: "Deury Valerio", correo: "dvalerio@cielosacusticos.com" },
  { nombre: "Digna Sanchez", correo: "dsanchez@cielosacusticos.com" },
  {
    nombre: "Dionelis Peguero",
    correo: "dpeguero@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Dionka Cabrera", correo: "dcabrera@cielosacusticos.com" },
  { nombre: "Edgar Viveros", correo: "eviveros@cielosacusticos.com" },
  {
    nombre: "Edison Cabrera Reynoso",
    correo: "ereynoso@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  { nombre: "Eduar Matos", correo: "ematos@cielosacusticos.com" },
  { nombre: "Eduardo Llanos", correo: "ellanos@cielosacusticos.com" },
  {
    nombre: "Elba Familia",
    correo: "efamilia@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "Elizabeth Carrasco",
    correo: "ecarrasco@cielosacusticos.com",
  },
  {
    nombre: "Emmanuel Apolinario",
    correo: "eapolinario@cielosacusticos.com",
    grupos: ["sucZonaOriental03"],
  },
  { nombre: "Emmanuel Sánchez", correo: "esanchez@cielosacusticos.com" },
  { nombre: "Enriquillo Castillo", correo: "ecastillo@cielosacusticos.com" },
  { nombre: "Esmerkin Paniagua", correo: "epaniagua@cielosacusticos.com" },
  {
    nombre: "Estefani Rodríguez",
    correo: "erodriguez@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Eva Martinez", correo: "emartinez@cielosacusticos.com" },
  {
    nombre: "Fanny Duarte",
    correo: "fduarte@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  { nombre: "Felipe Reyes", correo: "freyes@cielosacusticos.com" },
  {
    nombre: "Francis Joubert",
    correo: "fjoubert@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Frank Cepeda", correo: "fcepeda@cielosacusticos.com" },
  { nombre: "Frekner Martínez", correo: "fmartinez@cielosacusticos.com" },
  {
    nombre: "Genesis Hilario",
    correo: "ghilario@cielosacusticos.com",
    grupos: ["sucSantiago02"],
  },
  { nombre: "Gerson Cuevas", correo: "gcuevas@cielosacusticos.com" },
  {
    nombre: "Gimery Diaz",
    correo: "gdiaz@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  { nombre: "Glennys Sánchez", correo: "gsanchez@cielosacusticos.com" },
  {
    nombre: "Grace Mercedes",
    correo: "gmercedes@cielosacusticos.com",
    grupos: ["sucSantiago02"],
  },
  {
    nombre: "Guillermo Hernández",
    correo: "ghernandez@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "Hailyn Marcano",
    correo: "hmarcano@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  { nombre: "Hairo Angeles", correo: "hangeles@cielosacusticos.com" },
  {
    nombre: "Hederking Severino",
    correo: "hseverino@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Heidy Mieses", correo: "hmieses@cielosacusticos.com" },
  { nombre: "Hiara De La Rosa", correo: "hdelarosa@cielosacusticos.com" },
  { nombre: "Ignacio Contreras", correo: "icontreras@cielosacusticos.com" },
  { nombre: "Isaac Newton", correo: "inewton@cielosacusticos.com" },
  {
    nombre: "Isabel Cardozo",
    correo: "icardozo@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Isabel Severino Cruz", correo: "iseverino@cielosacusticos.com" },
  {
    nombre: "Issaura Estrella",
    correo: "iestrella@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "Jacqueline Victoria Santana",
    correo: "vsantana@cielosacusticos.com",
  },
  {
    nombre: "Yeltsin Vicioso",
    correo: "yvicioso@cielosacusticos.com",
    grupos: ["sucBavaro04", "proyectos05"],
  },
  { nombre: "Jairo A Reyes", correo: "jareyes@cielosacusticos.com" },
  { nombre: "Jarminson Marte", correo: "jmarte@cielosacusticos.com" },
  { nombre: "Jean Luis Acevedo", correo: "lacevedo@cielosacusticos.com" },
  {
    nombre: "Jenni Brito",
    correo: "jbrito@cielosacusticos.com",
    grupos: ["sucSantiago02"],
  },
  {
    nombre: "Jennifer Sanchez",
    correo: "jsanchez@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  {
    nombre: "Jenniffer Alcántara",
    correo: "asistente.compras@cielosacusticos.com",
  },
  {
    nombre: "Jennyffer Bourdierd",
    correo: "jbourdierd@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  {
    nombre: "Jessica Montes de Oca",
    correo: "jmontesdeoca@cielosacusticos.com",
    grupos: ["sucZonaOriental03"],
  },
  { nombre: "Jesus Mateo", correo: "jmateo@cielosacusticos.com" },
  {
    nombre: "Jhoel Taveras",
    correo: "jtaveras@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  { nombre: "Jhon Gonzalez", correo: "JGonzalez@cielosacusticos.com" },
  { nombre: "Jhon Gutierrez", correo: "jgutierrez@cielosacusticos.com" },
  { nombre: "Jiselle Ceballo", correo: "jceballo@cielosacusticos.com" },
  { nombre: "Joanna Damian", correo: "Jdamian@cielosacusticos.com" },
  {
    nombre: "Joanquín Medina Bautista",
    correo: "jbautista@cielosacusticos.com",
  },
  {
    nombre: "Joaquin Polanco",
    correo: "jpolanco@cielosacusticos.com",
    grupos: ["sucBavaro04", "proyectos05"],
  },

  { nombre: "Joel Vargas", correo: "jvargas@cielosacusticos.com" },
  {
    nombre: "Johanna Beato",
    correo: "Jbeato@cielosacusticos.com",
    grupos: ["sucSantiago02"],
  },
  { nombre: "José Alcántara", correo: "jalcantara@cielosacusticos.com" },
  { nombre: "Jose Enrique Mejia", correo: "jemejia@cielosacusticos.com" },
  { nombre: "José Manuel Reyes", correo: "jreyes@cielosacusticos.com" },
  { nombre: "Jose Perez", correo: "jperez@cielosacusticos.com" },
  {
    nombre: "Juan Francisco Rosario",
    correo: "frosario@cielosacusticos.com",
    grupos: ["sucBavaro04", "proyectos05"],
  },
  {
    nombre: "Francisco Feliz",
    correo: "ffeliz@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  {
    nombre: "Juan De Dios Cabada",
    correo: "jcabada@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Julio Martinez Lorenzo", correo: "jlorenzo@cielosacusticos.com" },
  {
    nombre: "Junior Perez Rosario",
    correo: "jrosario@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "Karla Gattas",
    correo: "kgattas@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "José Fernando Jiménez",
    correo: "fjimenez@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  { nombre: "Katherine Acosta", correo: "kacosta@cielosacusticos.com" },
  { nombre: "Kostia Rodriguez", correo: "krodriguez@cielosacusticos.com" },
  { nombre: "Laura Cristina Ortiz", correo: "lortiz@cielosacusticos.com" },
  { nombre: "Leury Fernández", correo: "lfernandez@cielosacusticos.com" },
  {
    nombre: "Lissy Encarnación",
    correo: "lencarnacion@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  {
    nombre: "Lucidalia Galva",
    correo: "lgalva@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  { nombre: "Luichy Diaz", correo: "ldiaz@cielosacusticos.com" },
  { nombre: "Luisa Betancourt", correo: "lbetancourt@cielosacusticos.com" },
  { nombre: "Manuel Alcantara", correo: "malcantara@cielosacusticos.com" },
  {
    nombre: "Manuela Volquez",
    correo: "mvolquez@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  { nombre: "Marcos Cortorreal", correo: "mcortorreal@cielosacusticos.com" },
  { nombre: "Mari Pily Bonilla", correo: "mpbonilla@cielosacusticos.com" },
  {
    nombre: "María Fernanda Martínez",
    correo: "mfmartinez@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Maria Taveras", correo: "mtaveras@cielosacusticos.com" },
  {
    nombre: "Maribel Meran",
    correo: "mmeran@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  {
    nombre: "Mariel Roa",
    correo: "mroa@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "Marielle Joubert",
    correo: "majoubert@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Marlene Bonilla", correo: "Mbonilla@cielosacusticos.com" },
  {
    nombre: "Marleny Reyes",
    correo: "mreyes@cielosacusticos.com",
    grupos: ["sucSantiago02"],
  },
  { nombre: "Mauricio Caro", correo: "mcaro@cielosacusticos.com" },
  {
    nombre: "Mayelin Pérez",
    correo: "mperez@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Mayerlin Capote", correo: "mcapote@cielosacusticos.com" },
  { nombre: "Melvin Bocio Díaz", correo: "mbocio@cielosacusticos.com" },
  {
    nombre: "Michelle Joubert",
    correo: "mjoubert@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  { nombre: "Milagros Cuevas", correo: "mcuevas@cielosacusticos.com" },
  { nombre: "Mirian Reynoso", correo: "mreynoso@cielosacusticos.com" },
  {
    nombre: "Mirielys Garcia",
    correo: "Mgarcia@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  { nombre: "Natalia Moreta", correo: "nmoreta@cielosacusticos.com" },
  {
    nombre: "Nestor Aviles",
    correo: "naviles@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  {
    nombre: "Nicolas Díaz",
    correo: "jdiaz@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  {
    nombre: "Norjalis Díaz",
    correo: "ndiaz@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "Octavio Mueses",
    correo: "omueses@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "Oliver Dominguez",
    correo: "odominguez@cielosacusticos.com",
    grupos: ["sucZonaOriental03"],
  },
  {
    nombre: "Oscar Morel",
    correo: "omorel@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  { nombre: "Pasante", correo: "pasante@cielosacusticos.com" },
  {
    nombre: "Pasante Contabilidad",
    correo: "Pasanteconta@cielosacusticos.com",
  },
  { nombre: "Pasante Mercadeo", correo: "pmercadeo@cielosacusticos.com" },
  {
    nombre: "Patricia Encarnación",
    correo: "pencarnacion@cielosacusticos.com",
  },
  {
    nombre: "Patricia Franceschi",
    correo: "pfranceschi@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Patricia Gonzalez", correo: "pgonzalez@cielosacusticos.com" },
  { nombre: "Pavel De Los Santos", correo: "pdelossantos@cielosacusticos.com" },
  {
    nombre: "Pedro Peña",
    correo: "ppena@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  { nombre: "Rafael Santana", correo: "rsantana@cielosacusticos.com" },
  { nombre: "Raul Caminero", correo: "rcaminero@cielosacusticos.com" },
  {
    nombre: "Richard Pache",
    correo: "rpache@cielosacusticos.com",
    grupos: ["sucBavaro04", "proyectos05"],
  },
  {
    nombre: "Ronald Ramos",
    correo: "rramos@cielosacusticos.com",
    grupos: ["sucSantiago02"],
  },
  { nombre: "Ronny Jiménez", correo: "rjimenez@cielosacusticos.com" },
  { nombre: "Rony De La Rosa", correo: "rodelarosa@cielosacusticos.com" },
  { nombre: "Rosa Soto", correo: "rsoto@cielosacusticos.com" },
  {
    nombre: "Rosangela De La Rosa",
    correo: "rdelarosa@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Rosmery Morillo", correo: "rmorillo@cielosacusticos.com" },
  { nombre: "Rosmery Romero", correo: "rromero@cielosacusticos.com" },
  {
    nombre: "Ruben Beltre",
    correo: "rbeltre@cielosacusticos.com",
    grupos: ["ventasPrincipal01"],
  },
  { nombre: "Rubén Delgado", correo: "rdelgado@cielosacusticos.com" },
  {
    nombre: "Ruth De León",
    correo: "rdeleon@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Ruth Esther Lara", correo: "cajapyl@cielosacusticos.com" },
  {
    nombre: "Sadra Feliz Pimentel",
    correo: "spimentel@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Sahi Peralta", correo: "speralta@cielosacusticos.com" },
  { nombre: "Samuel Mesa", correo: "caja@cielosacusticos.com" },
  { nombre: "Sarah Báez", correo: "sbaez@cielosacusticos.com" },
  { nombre: "Shaira Rodríguez", correo: "recepcion@cielosacusticos.com" },
  {
    nombre: "Silvia Pérez Peguero",
    correo: "sperez@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Sonia Morel", correo: "smorel@cielosacusticos.com" },
  { nombre: "Sorangel Lazala", correo: "gerente.compras@cielosacusticos.com" },
  { nombre: "Vanessa Gil", correo: "rgil@cielosacusticos.com" },
  { nombre: "Vladimir Carbonell", correo: "vcarbonell@cielosacusticos.com" },
  { nombre: "Waldy Paula", correo: "wpaula@cielosacusticos.com" },
  {
    nombre: "Warlen Nova",
    correo: "wnova@cielosacusticos.com",
    grupos: ["sucZonaOriental03"],
  },
  {
    nombre: "Miguel Martínez",
    correo: "mmartinez@cielosacusticos.com",
    grupos: ["sucBavaro04", "proyectos05"],
  },
  {
    nombre: "Wendy De La Cruz",
    correo: "wdelacruz@cielosacusticos.com",
    grupos: ["sucZonaOriental03"],
  },
  {
    nombre: "Winifer Peguero",
    correo: "wpeguero@cielosacusticos.com",
    grupos: ["proyectos05"],
  },
  {
    nombre: "Xavier Hernandez",
    correo: "xhernandez@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  {
    nombre: "Yanibel Reynoso",
    correo: "yreynoso@cielosacusticos.com",
    grupos: ["sucSantiago02"],
  },
  { nombre: "Yelissa Arnaud", correo: "yarnaud@cielosacusticos.com" },
  {
    nombre: "Yemelin Toribio",
    correo: "ytoribio@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
  { nombre: "Yeraldin Giron", correo: "ygiron@cielosacusticos.com" },
  {
    nombre: "Yohanny Altagracia López",
    correo: "cajazona@cielosacusticos.com",
    grupos: ["sucZonaOriental03"],
  },
  {
    nombre: "Yolanda Reyes",
    correo: "yreyes@cielosacusticos.com",
    grupos: ["sucZonaOriental03"],
  },
  { nombre: "Yonathan Nivar", correo: "ynivar@cielosacusticos.com" },
  {
    nombre: "Yuribert Ventura",
    correo: "yventura@cielosacusticos.com",
    grupos: ["sucBavaro04"],
  },
];
export const soloTodosCorreos = listaCorreos.map((user) => {
  return {
    ...user,
    grupos: user.grupos || [],
  };
});

export const TodosLosCorreosCielosDB = [...gruposCorreos, ...soloTodosCorreos];
