export const DataTableOrden = [
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
  {
    n: "",
    codigo: "",
    descripcion: "",
    qty: "",
    comentarios: "",
    qtyDisponible: "",
  },
];
