export const generatePlantilla = () => {
  const arrayA = [];
  for (let i = 0; i < 60; i++) {
    arrayA.push({
      n: "",
      codigo: "",
      descripcion: "",
      qty: "",
      comentarios: "",
      proyeccionDespachos: "",
    });
  }
  return arrayA;
  console.log(arrayA);
};

const PlantillaTablaMat = {
  inputs: [
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
    { n: "", codigo: "", descripcion: "", qty: "", comentarios: "" },
  ],
};
export default PlantillaTablaMat;

// Original
// const PlantillaTablaMat = {
//     inputs: [
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//       { N: "", Codigo: "", Descripcion: "", Qty: "", Comentarios: "" },
//     ],
//   };
//   export default PlantillaTablaMat;
