export default [
  {
    numeroDigitado: 1,
    tarima: 0,
    numeroItem: "NN01",
    descripcion:
      "Espejo 0.90 x 0.70  con frosting en borde superior e inferior ref: GY-5620",
    qty: 4,
    obs: "Imperfeccion en los bordes",
  },
  {
    numeroDigitado: 2,
    tarima: 0,
    numeroItem: "NN02",
    descripcion: "Espejo sencillo 0.6x0.8",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 3,
    tarima: 0,
    numeroItem: "NN03",
    descripcion: "Espejo con bases en esquinas 0.55x0.80",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 4,
    tarima: 0,
    numeroItem: "NN04",
    descripcion: "Espejo con base de metal trasera 0.5x1.0",
    qty: 2,
    obs: "Imperfeccion en los bordes",
  },
  {
    numeroDigitado: 5,
    tarima: 0,
    numeroItem: "NN05",
    descripcion: "Espejo con base trasera 1.0x0.75",
    qty: 1,
    obs: "Imperfeccion en los bordes",
  },
  {
    numeroDigitado: 6,
    tarima: 0,
    numeroItem: "NN06",
    descripcion: "Espejo con marco de madera maple lateral 0.5x0.60",
    qty: 2,
    obs: "Imperfeccion en los bordes",
  },
  {
    numeroDigitado: 7,
    tarima: 1,
    numeroItem: "NN07",
    descripcion: "Closet; Center Panel 282mm x 2082mm color:40719-b",
    qty: 8,
    obs: "2 cajas selladas de 4pcs",
  },
  {
    numeroDigitado: 8,
    tarima: 1,
    numeroItem: "NN08",
    descripcion: "Closet; Center Panel 282mm x 2082mm color: ver imagen",
    qty: 4,
    obs: "4 piezas sueltas buenas condiciones",
  },
  {
    numeroDigitado: 9,
    tarima: 1,
    numeroItem: "NN09",
    descripcion: "Closet; End Panel cherry oscuro 0.3x2.08",
    qty: 7,
    obs: "4unds con imperfecciones; humedad y torcidas",
  },
  {
    numeroDigitado: 10,
    tarima: 1,
    numeroItem: "NN10",
    descripcion: "Closet; Panel cherry oscuro 2.25x3.34",
    qty: 1,
    obs: "2unds ambas imperfectas, una de ella ya cortada, la otra presenta humedad",
  },
  {
    numeroDigitado: 11,
    tarima: 1,
    numeroItem: "NN11",
    descripcion: "Closet; Panel cherry oscuro 2.44x0.48",
    qty: 1,
    obs: "imperfeccion; humedad",
  },
  {
    numeroDigitado: 12,
    tarima: 1,
    numeroItem: "NN12",
    descripcion: "Closet; End Panel 550x2382mm",
    qty: 1,
    obs: "imperfeccion; humedad",
  },
  {
    numeroDigitado: 13,
    tarima: 1,
    numeroItem: "NN13",
    descripcion: "Closet; Panel cherry oscuro 2.82x0.53",
    qty: 2,
    obs: "Imperfeccion; ya instalado y humedad",
  },
  {
    numeroDigitado: 14,
    tarima: 1,
    numeroItem: "NN14",
    descripcion: "Panel cherry oscuro 2.82x0.55",
    qty: 1,
    obs: "humedad",
  },
  {
    numeroDigitado: 15,
    tarima: 1,
    numeroItem: "NN15",
    descripcion: "Closet; Panel cherry oscuro 2.25x055",
    qty: 1,
    obs: "Imperfeccion; usado",
  },
  {
    numeroDigitado: 16,
    tarima: 1,
    numeroItem: "NN16",
    descripcion: "Corner cabinet; Left & Right Backing 882&864x2382mm",
    qty: 6,
    obs: "3 cajas de 2pcs imperfeccion; humedad",
  },
  {
    numeroDigitado: 17,
    tarima: 1,
    numeroItem: "NN17",
    descripcion: "Listones de madera cherry oscuro 2.44x0.165",
    qty: 5,
    obs: "imperfeccion; humedad y deterioro",
  },
  {
    numeroDigitado: 18,
    tarima: 1,
    numeroItem: "NN18",
    descripcion: "Listones de madera cherry opaco 2.44x0.165",
    qty: 14,
    obs: "imperfeccion; humedad y deterioro",
  },
  {
    numeroDigitado: 19,
    tarima: 1,
    numeroItem: "NN19",
    descripcion: "Tabla fina 0.5cm cherry opaco usado 2.35x0.88x0.05",
    qty: 1,
    obs: "imperfeccion; usado y deterioro",
  },
  {
    numeroDigitado: 20,
    tarima: 1,
    numeroItem: "NN20",
    descripcion: "Tabla fina 0.5cm walnut 2.35x0.88x0.05",
    qty: 2,
    obs: "imperfecciones; ligeramente en los bordes",
  },
  {
    numeroDigitado: 21,
    tarima: 1,
    numeroItem: "NN21",
    descripcion: "Tabla fina 0.5cm cherry opaco 0.465x2.025",
    qty: 6,
    obs: "2unds buenas y 4 imperfectas; humedad, roto y deterioro",
  },
  {
    numeroDigitado: 22,
    tarima: 1,
    numeroItem: "NN22",
    descripcion: "Tabla fina 0.5cm cherry opaco 464x2320cm",
    qty: 4,
    obs: "imperfeccion; humedad,",
  },
  {
    numeroDigitado: 23,
    tarima: 1,
    numeroItem: "NN23",
    descripcion: "Tabla fina 0.5cm umbria 0.47x2.32",
    qty: 8,
    obs: "imperfeccion; humedad",
  },
  {
    numeroDigitado: 24,
    tarima: 1,
    numeroItem: "NN24",
    descripcion: "Tabla fina 0.5cm umbria 2.32x0.62",
    qty: 1,
    obs: "imperfeccion; humedad",
  },
  {
    numeroDigitado: 25,
    tarima: 1,
    numeroItem: "NN25",
    descripcion: "Tabla fina 0.5cm cherry oscuro 2.02x0.62",
    qty: 3,
    obs: "imperfeccion; humedad",
  },
  {
    numeroDigitado: 26,
    tarima: 1,
    numeroItem: "NN26",
    descripcion: "Tabla fina 0.5cm gris 0.46x2.3",
    qty: 4,
    obs: "imperfeccion; en su caja  pero con humedad",
  },
  {
    numeroDigitado: 27,
    tarima: 1,
    numeroItem: "NN27",
    descripcion: "Tabla fina 0.5cm cherry opaco 464x2320cm",
    qty: 3,
    obs: "imperfeccion; humedad",
  },
  {
    numeroDigitado: 28,
    tarima: 1,
    numeroItem: "NN28",
    descripcion: "Panel cherry oscuro 2.08x0.55",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 29,
    tarima: 1,
    numeroItem: "NN30",
    descripcion: "Closet; Big Panel color:OB-2 1220x2440",
    qty: 1,
    obs: "imperfeccion; humedad",
  },
  {
    numeroDigitado: 30,
    tarima: 2,
    numeroItem: "NN31",
    descripcion: "Closet; Center Panel 532x2382mm color; 40719-B",
    qty: 35,
    obs: "25 buenas mas 10 humedad",
  },
  {
    numeroDigitado: 31,
    tarima: 2,
    numeroItem: "NN32",
    descripcion: "Panel cherry oscuro 0.55x2.3 mt",
    qty: 2,
    obs: "humedad",
  },
  {
    numeroDigitado: 32,
    tarima: 2,
    numeroItem: "NN33",
    descripcion: "Closet; End Panel 550x2382mm color; 40719-B",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 33,
    tarima: 2,
    numeroItem: "NN34",
    descripcion: "Panel cherry oscuro 0.53x2.44",
    qty: 1,
    obs: "humedad",
  },
  {
    numeroDigitado: 34,
    tarima: 2,
    numeroItem: "NN35",
    descripcion: "Closet; Removable Shelf 600x282 color; OB-2",
    qty: 6,
    obs: "1 caja humedad de 6pcs",
  },
  {
    numeroDigitado: 35,
    tarima: 2,
    numeroItem: "NN36",
    descripcion: "Closet; Removable Shelf 0.860x0.282 color; OB-1",
    qty: 6,
    obs: "1 caja humedad de 6pcs",
  },
  {
    numeroDigitado: 36,
    tarima: 2,
    numeroItem: "NN37",
    descripcion: "Closet; Fixed Shelves 450x282 color; OB-1",
    qty: 8,
    obs: "1 caja de 8pcs",
  },
  {
    numeroDigitado: 37,
    tarima: 2,
    numeroItem: "NN38",
    descripcion: "Closet; Removable Shelf 450x282mm",
    qty: 6,
    obs: "1 caja de 6pcs",
  },
  {
    numeroDigitado: 38,
    tarima: 2,
    numeroItem: "NN39",
    descripcion: "Closet; Panel 0.86x0.28 removabled",
    qty: 10,
    obs: "humedad",
  },
  {
    numeroDigitado: 39,
    tarima: 2,
    numeroItem: "NN40",
    descripcion: "Fixed shelves 0.91x0.28",
    qty: 19,
    obs: "6unds buenas 13unds humedad",
  },
  {
    numeroDigitado: 40,
    tarima: 3,
    numeroItem: "NN41",
    descripcion: "Closet; Center Panel 532x2082 Color; OB-1",
    qty: 32,
    obs: "",
  },
  {
    numeroDigitado: 41,
    tarima: 3,
    numeroItem: "NN42",
    descripcion: "Closet; Center Panel 532x2382mm color; OB-1",
    qty: 6,
    obs: "5 buena mas 1und averias",
  },
  {
    numeroDigitado: 42,
    tarima: 3,
    numeroItem: "NN43",
    descripcion: "Closet; Backing 464x2020 color; OB-1",
    qty: 32,
    obs: "26 buenas 6 humedad",
  },
  {
    numeroDigitado: 43,
    tarima: 3,
    numeroItem: "NN44",
    descripcion: "Panel 0.55x2.0",
    qty: 2,
    obs: "imperfeccion; humedad y deterioro",
  },
  {
    numeroDigitado: 44,
    tarima: 3,
    numeroItem: "NN45",
    descripcion: "Panel liso 0.46x0.82 cherry oscuro",
    qty: 2,
    obs: "1 buena 1 imperfecciones leves",
  },
  {
    numeroDigitado: 45,
    tarima: 4,
    numeroItem: "EP02",
    descripcion: "Base cabinet B1P-BWPC-45 Oak (codigo cielos; 20066)",
    qty: 3,
    obs: "3 cajas buenas de una pieza",
  },
  {
    numeroDigitado: 46,
    tarima: 4,
    numeroItem: "EP03",
    descripcion: "Wall Cabinet W2P-BWPC-90",
    qty: 5,
    obs: "3 cajas completa mas 2 cajas incompleta",
  },
  {
    numeroDigitado: 47,
    tarima: 4,
    numeroItem: "EP04",
    descripcion: "Base  Cabinet B1P-BWPC-60 (codigo cielos;20035)",
    qty: 4,
    obs: "4 cajas completas",
  },
  {
    numeroDigitado: 48,
    tarima: 4,
    numeroItem: "EP05",
    descripcion: "Wall Cabinet W1P-BWPC-60 Oak ",
    qty: 5,
    obs: "5 cajas completas",
  },
  {
    numeroDigitado: 49,
    tarima: 4,
    numeroItem: "EP06",
    descripcion: "Tall cabinet D2P-BWPC-70 Color; Oak",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 50,
    tarima: 4,
    numeroItem: "EP07",
    descripcion: "Wall Cabinet W1P-BWPC-45 Oak (codigo cielos; 20061)",
    qty: 3,
    obs: "3 cajas completas",
  },
  {
    numeroDigitado: 51,
    tarima: 4,
    numeroItem: "EP08",
    descripcion: "Wall cabinet W1P-BWPC-30",
    qty: 2,
    obs: "2 cajas completas",
  },
  {
    numeroDigitado: 52,
    tarima: 5,
    numeroItem: "NN46",
    descripcion: "Base cabinet B1P-BWPC-45 Oak (codigo cielos; 20066)",
    qty: 32,
    obs: "cajas selladas",
  },
  {
    numeroDigitado: 53,
    tarima: 6,
    numeroItem: "NN47",
    descripcion: "Wall Cabinet W2P-BWPC-90 (codigo cielos; 20062)",
    qty: 35,
    obs: "cajas selladas",
  },
  {
    numeroDigitado: 54,
    tarima: 7,
    numeroItem: "NN48",
    descripcion: "Closet; Drawer 600x 500 OB-6",
    qty: 13,
    obs: "cajas selladas",
  },
  {
    numeroDigitado: 55,
    tarima: 7,
    numeroItem: "NN49",
    descripcion: "Closet; Drawer L handle 900x600 OB-6 ",
    qty: 28,
    obs: "7 cajas de 4 sets",
  },
  {
    numeroDigitado: 56,
    tarima: 7,
    numeroItem: "NN48B",
    descripcion: "Closet; Drawer 600x500 color; OB-6",
    qty: 8,
    obs: "2 cajas selladas de 4 sets",
  },
  {
    numeroDigitado: 57,
    tarima: 7,
    numeroItem: "NN49B",
    descripcion: "Closet; Drawer 600x500 color; OB-1",
    qty: 24,
    obs: "4 cajas de 6sets",
  },
  {
    numeroDigitado: 58,
    tarima: 7,
    numeroItem: "NN50",
    descripcion: "Closet; Drawer 450x500 OB-6",
    qty: 16,
    obs: "4 cajas de 4sets",
  },
  {
    numeroDigitado: 59,
    tarima: 8,
    numeroItem: "NN51",
    descripcion: "Closet; Drawer 600x600 color; OB-6",
    qty: 4,
    obs: "1 calla sellada de 4 set",
  },
  {
    numeroDigitado: 60,
    tarima: 8,
    numeroItem: "NN52",
    descripcion: "Corner Shelf removable 864x864 color; OB-4",
    qty: 12,
    obs: "3 cajas de 4 4pcs",
  },
  {
    numeroDigitado: 61,
    tarima: 8,
    numeroItem: "NN53",
    descripcion: "Corner cabinet; removable shelf 900x900 color;OB-6",
    qty: 4,
    obs: "1 caja de 4pcs dice fija a manuscrito",
  },
  {
    numeroDigitado: 62,
    tarima: 8,
    numeroItem: "NN54",
    descripcion: "Corner shelf removable 864x864 color; OB-6",
    qty: 5,
    obs: "imperfecciones ligeras",
  },
  {
    numeroDigitado: 63,
    tarima: 8,
    numeroItem: "NN55",
    descripcion: "Tope color; umbria (corner shelf OB-4)",
    qty: 6,
    obs: "imperfeccion; deterioro y usadas",
  },
  {
    numeroDigitado: 64,
    tarima: 9,
    numeroItem: "NN56",
    descripcion: "Bathroom cabinet FA3-303091 305x305x910 color; SY7052",
    qty: 9,
    obs: "9 cajas selladas",
  },
  {
    numeroDigitado: 65,
    tarima: 9,
    numeroItem: "NN57",
    descripcion: "Bathroom cabinet EM1-6080 600x18x800",
    qty: 6,
    obs: "6 cajas selladas",
  },
  {
    numeroDigitado: 66,
    tarima: 10,
    numeroItem: "NN58",
    descripcion: "Closet; Drawer 864x500 color; OB-1",
    qty: 80,
    obs: "16 cajas selladas de 5sets",
  },
  {
    numeroDigitado: 67,
    tarima: 11,
    numeroItem: "NN59",
    descripcion: "Closet; Drawer 900x600 color; OB-1",
    qty: 5,
    obs: "2 cajas de 4 set, una de ellas incompleta",
  },
  {
    numeroDigitado: 68,
    tarima: 11,
    numeroItem: "NN60",
    descripcion: "Closet; Drawer 900x600 color; OB-6",
    qty: 4,
    obs: "1 caja de 4 sets",
  },
  {
    numeroDigitado: 69,
    tarima: 11,
    numeroItem: "NN61",
    descripcion: "Closet; Drawer 864x500 color; 40719-B",
    qty: 1,
    obs: "1 caja de 6 sets",
  },
  {
    numeroDigitado: 70,
    tarima: 11,
    numeroItem: "NN62",
    descripcion: "Closet; Drawer 600x500",
    qty: 24,
    obs: "3 cajas de 4 sets mas 2 cajas de 6sets",
  },
  {
    numeroDigitado: 71,
    tarima: 11,
    numeroItem: "NN63",
    descripcion: "Closet; Trousers Shelves 600x500 OB-6",
    qty: 16,
    obs: "4 cajas de 4sets",
  },
  {
    numeroDigitado: 72,
    tarima: 11,
    numeroItem: "NN64",
    descripcion: "Closet; Fixed Shelves 600x531 color; OB-4",
    qty: 24,
    obs: "4 cajas de 6pcs",
  },
  {
    numeroDigitado: 73,
    tarima: 11,
    numeroItem: "NN65",
    descripcion: "Closet; Drawer 450x600 color; OB-2",
    qty: 8,
    obs: "2 cajas de 4 set",
  },
  {
    numeroDigitado: 74,
    tarima: 11,
    numeroItem: "NN66",
    descripcion: "Drawer 600x500",
    qty: 4,
    obs: "1 caja de 4set",
  },
  {
    numeroDigitado: 75,
    tarima: 11,
    numeroItem: "NN67",
    descripcion: "Drawer 600x600 color; OB-6",
    qty: 4,
    obs: "1 caja de 4set",
  },
  {
    numeroDigitado: 76,
    tarima: 11,
    numeroItem: "NN68",
    descripcion: "Removable shelves cherry opaco ",
    qty: 7,
    obs: "fuera de su caja",
  },
  {
    numeroDigitado: 77,
    tarima: 11,
    numeroItem: "NN69",
    descripcion: "Closet; Drawer 450x600 OB-6",
    qty: 12,
    obs: "3 cajas de 4set",
  },
  {
    numeroDigitado: 78,
    tarima: 11,
    numeroItem: "NN70",
    descripcion: "Closet; Tie Storage Box OB-6 (600x500mm) ",
    qty: 32,
    obs: "8 cajas de 4 sets",
  },
  {
    numeroDigitado: 79,
    tarima: 11,
    numeroItem: "NN71",
    descripcion: "Trouser Shelves 600x500 color; OB-6",
    qty: 4,
    obs: "1 caja de 4set",
  },
  {
    numeroDigitado: 80,
    tarima: 12,
    numeroItem: "NN72",
    descripcion: "Closet; Fixed Shelves 900x531 color; OB-4",
    qty: 1,
    obs: "1 caja dice RF a manuscrito",
  },
  {
    numeroDigitado: 81,
    tarima: 12,
    numeroItem: "NN73",
    descripcion: "Fixed shelves 864x562 color; OB-6",
    qty: 12,
    obs: "12pcs usadas",
  },
  {
    numeroDigitado: 82,
    tarima: 12,
    numeroItem: "NN74",
    descripcion: "Closet; Fixed shelves 864x532 color; OB-1",
    qty: 12,
    obs: "dice Removible a manuscrito 2 cajas de 6sets",
  },
  {
    numeroDigitado: 83,
    tarima: 12,
    numeroItem: "NN75",
    descripcion: "Shelves fixed 864x532 OB-1",
    qty: 1,
    obs: "1 caja, sin etiqueta del fabricante",
  },
  {
    numeroDigitado: 84,
    tarima: 12,
    numeroItem: "NN76",
    descripcion: "no existe",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 85,
    tarima: 12,
    numeroItem: "NN77",
    descripcion: "Shelves fixed 864x532 OB-1",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 86,
    tarima: 12,
    numeroItem: "NN78",
    descripcion: "Shelves fixed 0.45x0.53",
    qty: 11,
    obs: "imperfecta; deterioro",
  },
  {
    numeroDigitado: 87,
    tarima: 12,
    numeroItem: "NN79",
    descripcion: "Shelves removible 0.45x053 OB-1",
    qty: 11,
    obs: "imperfecta ligeramente",
  },
  {
    numeroDigitado: 88,
    tarima: 12,
    numeroItem: "NN80",
    descripcion: "Shelf Removible 0.45x0.53 OB-6",
    qty: 3,
    obs: "imperfecta deterioro",
  },
  {
    numeroDigitado: 89,
    tarima: 13,
    numeroItem: "NN81",
    descripcion: "Closet; Drawer 864x500 color; OB-1",
    qty: 70,
    obs: "14 cajas de 5sets",
  },
  {
    numeroDigitado: 90,
    tarima: 14,
    numeroItem: "NN82",
    descripcion: "Bathroom Cabinet FP7H-45255 color; FJQ12119",
    qty: 23,
    obs: "cajas selladas",
  },
  {
    numeroDigitado: 91,
    tarima: 14,
    numeroItem: "NN83",
    descripcion: "Bathroom Cabinet FBOT-2 801540 800x150x400 color; JQ18221",
    qty: 5,
    obs: "4 cajas selladas mas 1 caja abierta",
  },
  {
    numeroDigitado: 92,
    tarima: 14,
    numeroItem: "NN84",
    descripcion: "Bathroom 500x150x600 FA2-501560 color; JQ18221",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 93,
    tarima: 14,
    numeroItem: "NN85",
    descripcion: "Bathroom cabinet FA3-303091 305x305x910 color; FJQ12119",
    qty: 1,
    obs: "1 caja abierta",
  },
  {
    numeroDigitado: 94,
    tarima: 14,
    numeroItem: "NN86",
    descripcion: "Tabla de planchar para closet",
    qty: 2,
    obs: "1 caja sellada, otra sin caja y con humedad",
  },
  {
    numeroDigitado: 95,
    tarima: 15,
    numeroItem: "NN87",
    descripcion: "Bathroom cabinet FM3H-793850 Q18221",
    qty: 24,
    obs: "24 cajas selladas",
  },
  {
    numeroDigitado: 96,
    tarima: 16,
    numeroItem: "NN88",
    descripcion: "Wall cabinet W1P-BWPC-45",
    qty: 22,
    obs: "22 cajas selladas",
  },
  {
    numeroDigitado: 97,
    tarima: 17,
    numeroItem: "NN89",
    descripcion:
      "Botiquin ref BY-866 con espejo Oak 125x70x19cm (codigo cielos; 20042)",
    qty: 7,
    obs: "4 rotos 3 buenos",
  },
  {
    numeroDigitado: 98,
    tarima: 18,
    numeroItem: "NN90",
    descripcion: "Wall cabinet W1P-BWPC-30 oak (codigo cielos;20079)",
    qty: 10,
    obs: "10 cajas selladas",
  },
  {
    numeroDigitado: 99,
    tarima: 18,
    numeroItem: "NN91",
    descripcion: "Base cabinet w/ Drawer B4GD-BWPC-45 (codigo cielos; 20052)",
    qty: 5,
    obs: "5 cajas selladas",
  },
  {
    numeroDigitado: 100,
    tarima: 18,
    numeroItem: "NN92",
    descripcion: "Wall cabinet W1P-BWPC-60 Oak ",
    qty: 11,
    obs: "11 cajas",
  },
  {
    numeroDigitado: 101,
    tarima: 19,
    numeroItem: "NN93",
    descripcion:
      "Mobiliario negro BY-861 (1545x445x360) negro (codigo cielos; 20046)",
    qty: 7,
    obs: "7 cajas selladas",
  },
  {
    numeroDigitado: 102,
    tarima: 20,
    numeroItem: "NN94",
    descripcion: "Gabinete negro c/espejo BY-856 (codigo cielos; 20056)",
    qty: 20,
    obs: "20 cajas buenas pero tornillos con mojo",
  },
  {
    numeroDigitado: 103,
    tarima: 21,
    numeroItem: "NN95",
    descripcion: "Gabinete blanco c/espejo BY-856",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 104,
    tarima: 22,
    numeroItem: "NN96",
    descripcion: "Lavamano 820x400 ref:9393 ",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 105,
    tarima: 22,
    numeroItem: "NN97",
    descripcion: "Lavamano de cristal frosting cuadrado 0.41x0.41",
    qty: 1,
    obs: "imperfecto",
  },
  {
    numeroDigitado: 106,
    tarima: 22,
    numeroItem: "NN98",
    descripcion:
      "Lavamano de cristal frosting rectangular borde redondeados 0.57x0.36",
    qty: 1,
    obs: "imperfecto",
  },
  {
    numeroDigitado: 107,
    tarima: 22,
    numeroItem: "NN99",
    descripcion: "Lavamano de cristal redondo transparente 0.42m de radio",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 108,
    tarima: 22,
    numeroItem: "NN100",
    descripcion: "Lavamano de cristal redondo rojo  0.3m",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 109,
    tarima: 23,
    numeroItem: "NN101",
    descripcion: "Accesorio closet; Bandeja",
    qty: 18,
    obs: "16 en su caja 2 fuera de su caja pero buenas",
  },
  {
    numeroDigitado: 110,
    tarima: 23,
    numeroItem: "NN102",
    descripcion: "Espejo con marco de madera negro 0.56x0.91 ref: 802-3",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 111,
    tarima: 23,
    numeroItem: "NN103",
    descripcion: "Wall Cabinet W2P-BWPC-90 white",
    qty: 1,
    obs: "1 caja",
  },
  {
    numeroDigitado: 112,
    tarima: 23,
    numeroItem: "NN104",
    descripcion: "Tanque de inodoro roto, NO COLOCAR",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 113,
    tarima: 23,
    numeroItem: "NN105",
    descripcion: "Mezcladora para fregadero B2MH-EX1C",
    qty: 4,
    obs: "1 caja de 4pcs",
  },
  {
    numeroDigitado: 114,
    tarima: 24,
    numeroItem: "NN106",
    descripcion:
      "Mobiliario negro BY-863BL 1245x575x455mm  (codigo cielos;20034)",
    qty: 4,
    obs: "4 buenos",
  },
  {
    numeroDigitado: 115,
    tarima: 24,
    numeroItem: "NN107",
    descripcion:
      "Set de accesorios de baño AIV-0006-K3P (codigo cielos; 20080)",
    qty: 44,
    obs: "44 sets",
  },
  {
    numeroDigitado: 116,
    tarima: 25,
    numeroItem: "NN108",
    descripcion: "Bathroom cabinet FA2-501560  500x150x600 color; FJQ12119",
    qty: 3,
    obs: "3 cajas selladas",
  },
  {
    numeroDigitado: 117,
    tarima: 25,
    numeroItem: "NN109",
    descripcion: "Bathroom cabinet FP7H-45255 color; Q18221",
    qty: 5,
    obs: "5 cajas selladas",
  },
  {
    numeroDigitado: 118,
    tarima: 25,
    numeroItem: "NN110",
    descripcion: "Espejo 802-3",
    qty: 4,
    obs: "4 buenos (tomar foto del 102)",
  },
  {
    numeroDigitado: 119,
    tarima: 25,
    numeroItem: "NN111",
    descripcion: "Muebel oak BY-825",
    qty: 2,
    obs: "2 buenos",
  },
  {
    numeroDigitado: 120,
    tarima: 25,
    numeroItem: "NN112",
    descripcion: "Mezcladora B2M-CL2C",
    qty: 32,
    obs: "32 buenas",
  },
  {
    numeroDigitado: 121,
    tarima: 25,
    numeroItem: "NN113",
    descripcion: "Mezcladora B2M-CL1C",
    qty: 8,
    obs: "8unds buenas",
  },
  {
    numeroDigitado: 122,
    tarima: 26,
    numeroItem: "NN114",
    descripcion: "Closet; Drawer 864x500 color; 40719-B",
    qty: 6,
    obs: "5 cajas selladas de 6sets mas 1 caja aiertas de 6 set",
  },
  {
    numeroDigitado: 123,
    tarima: 26,
    numeroItem: "NN115",
    descripcion: "Drawer 600x500 OB-4",
    qty: 5,
    obs: "5 cajas selladas",
  },
  {
    numeroDigitado: 124,
    tarima: 26,
    numeroItem: "NN116",
    descripcion: "Shelf removable 864x864 color;40719-B",
    qty: 1,
    obs: "1 caja de 4pcs",
  },
  {
    numeroDigitado: 125,
    tarima: 26,
    numeroItem: "NN117",
    descripcion: "Tope usado cherry oscuro forma con esquina menos fixed",
    qty: 4,
    obs: "4unds usadas e imperfectas",
  },
  {
    numeroDigitado: 126,
    tarima: 26,
    numeroItem: "NN118",
    descripcion: "Conjunto de piezas sin identificar varios",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 127,
    tarima: 27,
    numeroItem: "NN119",
    descripcion: "Zapatera accesorio closet F248-900 (codigo cielos; 20131)",
    qty: 18,
    obs: "13 en su caja mas 5 fuera de sus cajas",
  },
  {
    numeroDigitado: 128,
    tarima: 27,
    numeroItem: "NN120",
    descripcion: "Accesorio de closet; Espejo F01",
    qty: 1,
    obs: "buenos",
  },
  {
    numeroDigitado: 129,
    tarima: 28,
    numeroItem: "NN121",
    descripcion: "Lavamano OK-1079",
    qty: 4,
    obs: "buenos",
  },
  {
    numeroDigitado: 130,
    tarima: 28,
    numeroItem: "NN122",
    descripcion: "Lavamano OK-1128",
    qty: 7,
    obs: "buenos",
  },
  {
    numeroDigitado: 131,
    tarima: 29,
    numeroItem: "NN123",
    descripcion: "Lavamano 7846 (470x460x160) (codigo cielos; 20077",
    qty: 18,
    obs: "buenos",
  },
  {
    numeroDigitado: 132,
    tarima: 29,
    numeroItem: "NN124",
    descripcion: "Lavamano 7243 (codigo cielos; 20065)",
    qty: 8,
    obs: "",
  },
  {
    numeroDigitado: 133,
    tarima: 29,
    numeroItem: "NN125",
    descripcion: "Lavamano 1579",
    qty: 6,
    obs: "",
  },
  {
    numeroDigitado: 134,
    tarima: 30,
    numeroItem: "NN126",
    descripcion: "Lavamano ref; 918 (codigo cielos; 20038)",
    qty: 6,
    obs: "",
  },
  {
    numeroDigitado: 135,
    tarima: 31,
    numeroItem: "NN127",
    descripcion:
      "Lavamano cuadrado borde redondeado de cristal transparente 0.43x0.43",
    qty: 1,
    obs: "1und imperfecta",
  },
  {
    numeroDigitado: 136,
    tarima: 31,
    numeroItem: "NN128",
    descripcion: "Lavamano de cristal redondo transparente 0.42m de radio",
    qty: 11,
    obs: "11unds buenos",
  },
  {
    numeroDigitado: 137,
    tarima: 31,
    numeroItem: "NN129",
    descripcion: "Lavamano de cristal redondo frosting 0.42m ",
    qty: 4,
    obs: "4unds buenos",
  },
  {
    numeroDigitado: 138,
    tarima: 31,
    numeroItem: "NN130",
    descripcion: "Lavamano rojo de cristal redondo 0.31m",
    qty: 21,
    obs: "buenos",
  },
  {
    numeroDigitado: 139,
    tarima: 31,
    numeroItem: "NN131",
    descripcion: "Lavamano de cristal verde claro (ref: CBA85056)",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 140,
    tarima: 32,
    numeroItem: "NN132",
    descripcion: "Espejo 90x60 GY-5645",
    qty: 25,
    obs: "buenos",
  },
  {
    numeroDigitado: 141,
    tarima: 33,
    numeroItem: "NN133",
    descripcion: "Bathroom cabinet FM11H-M-705",
    qty: 26,
    obs: "26 cajas de 1pcs",
  },
  {
    numeroDigitado: 142,
    tarima: 33,
    numeroItem: "NN134",
    descripcion: "no existe",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 143,
    tarima: 34,
    numeroItem: "NN135",
    descripcion: "Base cabinet w/drawer (20082) B4GO-BWPC-45",
    qty: 9,
    obs: "9unds cajas selladas",
  },
  {
    numeroDigitado: 144,
    tarima: 34,
    numeroItem: "NN136",
    descripcion: "Lavamano 420x290x150 (20081)",
    qty: 5,
    obs: "buenos",
  },
  {
    numeroDigitado: 145,
    tarima: 34,
    numeroItem: "NN137",
    descripcion: "Lavamano cuadrado 7907 (codigo cielos; 200032)",
    qty: 4,
    obs: "buenos",
  },
  {
    numeroDigitado: 146,
    tarima: 34,
    numeroItem: "NN138",
    descripcion: "Lavamano redondo de cristal verde 0.42m",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 147,
    tarima: 34,
    numeroItem: "NN139",
    descripcion: "Corbatera F12L",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 148,
    tarima: 34,
    numeroItem: "NN140",
    descripcion: "Lavamano 7911 (ref;20063) rectangular",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 149,
    tarima: 35,
    numeroItem: "NN141",
    descripcion: "Estante para closet F24A",
    qty: 16,
    obs: "buenos",
  },
  {
    numeroDigitado: 150,
    tarima: 36,
    numeroItem: "NN142",
    descripcion: "Lavamano cuadrado 66-130 (codigo cielos; 20096)",
    qty: 9,
    obs: "buenos",
  },
  {
    numeroDigitado: 151,
    tarima: 36,
    numeroItem: "NN143",
    descripcion: "Lavamano forma corazon ref; OK-1526 (codigo cielos; 20105)",
    qty: 9,
    obs: "buenos",
  },
  {
    numeroDigitado: 152,
    tarima: 36,
    numeroItem: "NN144",
    descripcion: "Lavamano cuadrado ref: 7821 (codigo cielos; 20091)",
    qty: 3,
    obs: "buenos",
  },
  {
    numeroDigitado: 153,
    tarima: 36,
    numeroItem: "NN145",
    descripcion: "Lavamano ref; 3004 ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 154,
    tarima: 36,
    numeroItem: "NN146",
    descripcion: "Mezcladora para fregadero B2MH-M1C",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 155,
    tarima: 37,
    numeroItem: "NN147",
    descripcion: "Mueble color oscuro BY-803 imperfecto 2unds",
    qty: 2,
    obs: "imperfectos; humedad, manchas",
  },
  {
    numeroDigitado: 156,
    tarima: 38,
    numeroItem: "NN148",
    descripcion: "Espejo de closet",
    qty: 22,
    obs: "buenos",
  },
  {
    numeroDigitado: 157,
    tarima: 39,
    numeroItem: "NN149",
    descripcion: "Espejo GY-5645",
    qty: 20,
    obs: "",
  },
  {
    numeroDigitado: 158,
    tarima: 39,
    numeroItem: "NN172",
    descripcion: "Pieza de pvc varias",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 159,
    tarima: 40,
    numeroItem: "NN150",
    descripcion: "Bañeras forma de jacuzzi",
    qty: 40,
    obs: "No pudimos identificar cuantas averias",
  },
  {
    numeroDigitado: 160,
    tarima: 41,
    numeroItem: "NN151",
    descripcion: "Tabla de planchar para closet",
    qty: 5,
    obs: "imperfecta; metal con corrosion",
  },
  {
    numeroDigitado: 161,
    tarima: 41,
    numeroItem: "NN152",
    descripcion: "Accesorio de closet; Estante F24 (codigo cielos; 20124)",
    qty: 5,
    obs: "7 cajas selladas",
  },
  {
    numeroDigitado: 162,
    tarima: 41,
    numeroItem: "NN153",
    descripcion: "Mezcladora (codigo cielos; 20132)",
    qty: 56,
    obs: "buenas",
  },
  {
    numeroDigitado: 163,
    tarima: 41,
    numeroItem: "NN154",
    descripcion: "Corbatera F11-L",
    qty: 21,
    obs: "buenas",
  },
  {
    numeroDigitado: 164,
    tarima: 41,
    numeroItem: "NN155",
    descripcion: "Llave de lavamano  ref; 12004T3",
    qty: 52,
    obs: "buenas",
  },
  {
    numeroDigitado: 165,
    tarima: 42,
    numeroItem: "NN156",
    descripcion: "Lavamano OK-1570 (codigo cielos; 20048)",
    qty: 3,
    obs: "buenas",
  },
  {
    numeroDigitado: 166,
    tarima: 42,
    numeroItem: "NN157",
    descripcion: "Lavamano ref; 7509",
    qty: 8,
    obs: "buenas",
  },
  {
    numeroDigitado: 167,
    tarima: 42,
    numeroItem: "NN158",
    descripcion: "Lavamano peq con mezcladora sin ref 0.34x0.30",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 168,
    tarima: 43,
    numeroItem: "NN159",
    descripcion: "Lavamano CHNS-5004 color Ivory (050910)",
    qty: 10,
    obs: "buenos",
  },
  {
    numeroDigitado: 169,
    tarima: 44,
    numeroItem: "NN160",
    descripcion: "Lavamano basin BY-835 530x530x240mm",
    qty: 4,
    obs: "buenos",
  },
  {
    numeroDigitado: 170,
    tarima: 45,
    numeroItem: "NN161",
    descripcion: "Mueble BY-825 negro ",
    qty: 1,
    obs: "imperfecciones leves, corrosion en tornillos",
  },
  {
    numeroDigitado: 171,
    tarima: 45,
    numeroItem: "NN162",
    descripcion: "Bathroom cabinet FA1-401515",
    qty: 24,
    obs: "cajas selladas",
  },
  {
    numeroDigitado: 172,
    tarima: 45,
    numeroItem: "NN163",
    descripcion: "Bathroom cabinet FBOT-1 JQ1821",
    qty: 21,
    obs: "cajas selladas",
  },
  {
    numeroDigitado: 173,
    tarima: 46,
    numeroItem: "NN164",
    descripcion: "Lavamano cristal frosting Baxcy 0.46m",
    qty: 3,
    obs: "buenos",
  },
  {
    numeroDigitado: 174,
    tarima: 46,
    numeroItem: "NN165",
    descripcion: "Lavamano baxcy cristal transparente",
    qty: 5,
    obs: "buenos",
  },
  {
    numeroDigitado: 175,
    tarima: 46,
    numeroItem: "NN166",
    descripcion: "Lavamano cuadrado de cristal baxcy 2und bueno",
    qty: 2,
    obs: "buenos",
  },
  {
    numeroDigitado: 176,
    tarima: 46,
    numeroItem: "NN167",
    descripcion: "Lavamano rojo de cristal redondo 0.3m (ref;CBA82138)",
    qty: 4,
    obs: "buenos",
  },
  {
    numeroDigitado: 177,
    tarima: 46,
    numeroItem: "NN168",
    descripcion: "Pieza no identificada",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 178,
    tarima: 46,
    numeroItem: "NN169",
    descripcion: "Siphon de lavamano",
    qty: 143,
    obs: "",
  },
  {
    numeroDigitado: 179,
    tarima: 47,
    numeroItem: "NN170",
    descripcion: "Siphon de lavamano",
    qty: 304,
    obs: "",
  },
  {
    numeroDigitado: 180,
    tarima: 47,
    numeroItem: "NN171",
    descripcion: "Baterias de 3.6voltios",
    qty: 16,
    obs: "",
  },
  {
    numeroDigitado: 181,
    tarima: 48,
    numeroItem: "NN173",
    descripcion: "Lavamano transparente de cristal 1.0x0.6m",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 182,
    tarima: 48,
    numeroItem: "NN174",
    descripcion: "Lavamano de cristal frosting 0.75x0.64m",
    qty: 2,
    obs: "1bueno mas 1 averias",
  },
  {
    numeroDigitado: 183,
    tarima: 49,
    numeroItem: "NN175",
    descripcion: "Lavamano 7911 (codigo cielos 20095) rectangular",
    qty: 6,
    obs: "",
  },
  {
    numeroDigitado: 184,
    tarima: 49,
    numeroItem: "NN176",
    descripcion: "Lavamano de cristal verdoso (codigo cielos 20094)",
    qty: 19,
    obs: "",
  },
  {
    numeroDigitado: 185,
    tarima: 49,
    numeroItem: "NN177",
    descripcion: "Lavamano rectangular 0.61x0.45",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 186,
    tarima: 50,
    numeroItem: "NN178",
    descripcion: "Espejo GY-5645",
    qty: 15,
    obs: "",
  },
  {
    numeroDigitado: 187,
    tarima: 51,
    numeroItem: "NN179",
    descripcion: "Lavamano CBA-1000 cristal frosting",
    qty: 18,
    obs: "",
  },
  {
    numeroDigitado: 188,
    tarima: 51,
    numeroItem: "NN180",
    descripcion: "Lavamano de cristal frosting CBA82139",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 189,
    tarima: 51,
    numeroItem: "NN181",
    descripcion: "Bathroom cabinet FA1-401515",
    qty: 30,
    obs: "",
  },
  {
    numeroDigitado: 190,
    tarima: 51,
    numeroItem: "NN182",
    descripcion:
      "Gabinete de baño con espejo blanco BY856 (codigo cielos; 20138)",
    qty: 30,
    obs: "",
  },
  {
    numeroDigitado: 191,
    tarima: 52,
    numeroItem: "NN183",
    descripcion: "Lavamano de cristal cuadrado misma ref CBA-8400 dos tipos",
    qty: 27,
    obs: "esquinas redondeadas y esquinas normales",
  },
  {
    numeroDigitado: 192,
    tarima: 53,
    numeroItem: "NN184",
    descripcion: "Bathroom cabinet FBOT-1 // FJQ12119",
    qty: 35,
    obs: "35unds en su caja",
  },
  {
    numeroDigitado: 193,
    tarima: 53,
    numeroItem: "NN185",
    descripcion: "Mango de puerta plateado redondeado ref; T330-S34P3",
    qty: 38,
    obs: "38 pares",
  },
  {
    numeroDigitado: 194,
    tarima: 53,
    numeroItem: "NN186",
    descripcion: "Mango de puerta plateado cuadrado ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 195,
    tarima: 53,
    numeroItem: "NN187",
    descripcion: "Mango de puerta plateado cuadrado ",
    qty: 10,
    obs: "comienzo de corrosion",
  },
  {
    numeroDigitado: 196,
    tarima: 53,
    numeroItem: "NN188",
    descripcion: "Mango de puerta 0.56x0.10",
    qty: 30,
    obs: "comienzo de corrosion",
  },
  {
    numeroDigitado: 197,
    tarima: 53,
    numeroItem: "NN189",
    descripcion: "Accesorios de closet (codigo cielos; 26048) F13-370",
    qty: 9,
    obs: "",
  },
  {
    numeroDigitado: 198,
    tarima: 54,
    numeroItem: "NN190",
    descripcion: "Base cabinet B2P-BWPC-90 oak (codigo cielos; 20057)",
    qty: 38,
    obs: "cajas selladas",
  },
  {
    numeroDigitado: 199,
    tarima: 54,
    numeroItem: "NN191",
    descripcion:
      "Base cabinet w/ Drawer B2P-BWPC-90 oak (codigo cielos; 20033)",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 200,
    tarima: 54,
    numeroItem: "NN192",
    descripcion: "Bathroom cabinet FA2-501560 JQ18221 500x150x600",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 201,
    tarima: 54,
    numeroItem: "NN193",
    descripcion: "Bathroom cabinet FA2-501560  500x150x600 color; SY7052",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 202,
    tarima: 54,
    numeroItem: "NN194",
    descripcion: "Bathroom cabinet F42-501560 color; SY7052",
    qty: 7,
    obs: "7 cajas selladas",
  },
  {
    numeroDigitado: 203,
    tarima: 55,
    numeroItem: "NN195",
    descripcion: "Bathroom cabinet FA-11-705225 color; SY7052 700x520x250",
    qty: 8,
    obs: "",
  },
  {
    numeroDigitado: 204,
    tarima: 55,
    numeroItem: "NN196",
    descripcion: "Closet; Drawer OB-2 900x600",
    qty: 16,
    obs: "4 cajas de 4 sets",
  },
  {
    numeroDigitado: 205,
    tarima: 55,
    numeroItem: "NN197",
    descripcion: "Bathroom cab FBOT-1 color; FJQ12119",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 206,
    tarima: 55,
    numeroItem: "NN198",
    descripcion: "Bathroom cab FM3H593850 color; SY7052 590x380x500",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 207,
    tarima: 56,
    numeroItem: "NN199",
    descripcion: "Llave de lavamano delay action (BTD109-1)",
    qty: 129,
    obs: "",
  },
  {
    numeroDigitado: 208,
    tarima: 56,
    numeroItem: "NN200",
    descripcion:
      "Bathroom Cabinet FBOT-2 801540 800x150x400 color; JQ18221 (codigo cielos; 20155)",
    qty: 8,
    obs: "",
  },
  {
    numeroDigitado: 209,
    tarima: 57,
    numeroItem: "NN201",
    descripcion: "Lavamano negro cuadrado 0.45x0.45",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 210,
    tarima: 57,
    numeroItem: "NN202",
    descripcion: "Lavamano ref; P7509",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 211,
    tarima: 57,
    numeroItem: "NN203",
    descripcion: "Lavamano 0.44x0.44 OK-1570",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 212,
    tarima: 58,
    numeroItem: "NN204",
    descripcion: "Lavamano charns CH2-ARM2W",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 213,
    tarima: 58,
    numeroItem: "NN204B",
    descripcion: "Lavamano OK-0386 0.51m",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 214,
    tarima: 58,
    numeroItem: "NN205",
    descripcion: "Lavamano de cristal GY2021",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 215,
    tarima: 58,
    numeroItem: "NN206",
    descripcion: "Lavamano circular de cristal con diseño BX2023",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 216,
    tarima: 58,
    numeroItem: "NN207",
    descripcion: "Lavamano de cristal con petalos rojos BX2023RJ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 217,
    tarima: 58,
    numeroItem: "NN208",
    descripcion: "Lavamano OK04333",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 218,
    tarima: 59,
    numeroItem: "NN209",
    descripcion: "Lavamano cuadrado 0.42x0.42 (P70988)",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 219,
    tarima: 59,
    numeroItem: "NN210",
    descripcion: "Lavamano redondo OK-1146",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 220,
    tarima: 59,
    numeroItem: "NN211",
    descripcion: "Lavamano CHNS-5001 redondo",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 221,
    tarima: 59,
    numeroItem: "NN212",
    descripcion: "Lavamano OK-1079",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 222,
    tarima: 60,
    numeroItem: "NN213",
    descripcion: "Lavamano OK1539",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 223,
    tarima: 60,
    numeroItem: "NN214",
    descripcion: "Lavamano OK1570",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 224,
    tarima: 60,
    numeroItem: "NN215",
    descripcion: "Lavamano OK0477",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 225,
    tarima: 60,
    numeroItem: "NN216",
    descripcion: "Lavamano OK1159",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 226,
    tarima: 40,
    numeroItem: "NN217",
    descripcion: "Lavamano OK1146",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 227,
    tarima: 40,
    numeroItem: "NN218",
    descripcion: "Lavamano OK1144",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 228,
    tarima: 40,
    numeroItem: "NN219",
    descripcion: "Lavamano OK0475",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 229,
    tarima: 40,
    numeroItem: "NN220",
    descripcion: "Lavamano OK1339",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 230,
    tarima: 61,
    numeroItem: "NN221",
    descripcion: "Set de accesorios de baño AIV-0006-K6P",
    qty: 18,
    obs: "",
  },
  {
    numeroDigitado: 231,
    tarima: 61,
    numeroItem: "NN222",
    descripcion:
      "Set de accesorios de baño AIV-0006-K3P (codigo cielos; 20080)",
    qty: 20,
    obs: "",
  },
  {
    numeroDigitado: 232,
    tarima: 61,
    numeroItem: "NN223",
    descripcion: "Rollo no identificado",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 233,
    tarima: 61,
    numeroItem: "NN224",
    descripcion: "Lavamano de cristal CBA1006-1",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 234,
    tarima: 61,
    numeroItem: "NN225",
    descripcion: "Lavamano de cristal cuadrado CBA84001-1",
    qty: 1,
    obs: "1und imperfecta",
  },
  {
    numeroDigitado: 235,
    tarima: 61,
    numeroItem: "NN226",
    descripcion: "Lavamano de cristal (codigo de cielos; 20158)",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 236,
    tarima: 61,
    numeroItem: "NN227",
    descripcion: "Lavamano cuadrado ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 237,
    tarima: 61,
    numeroItem: "NN228",
    descripcion: "Lavamano CBA1006-1 de cristal redondo",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 238,
    tarima: 61,
    numeroItem: "NN229",
    descripcion: "Lavamano rojo de cristal redondo 0.3",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 239,
    tarima: 61,
    numeroItem: "NN230",
    descripcion: "Caja con pieza no identificada",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 240,
    tarima: 61,
    numeroItem: "NN231",
    descripcion: "Estante de closet multi proposito",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 241,
    tarima: 61,
    numeroItem: "NN232",
    descripcion: "Accesorio para closet F26-900",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 242,
    tarima: 61,
    numeroItem: "NN233",
    descripcion: "Estante para closet multi uso",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 243,
    tarima: 61,
    numeroItem: "NN234",
    descripcion: "Mezcladora para fregadero B2MH-M1C",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 244,
    tarima: 61,
    numeroItem: "NN235",
    descripcion: "Mezcladora para fregadero (codigo cielos; 20073)",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 245,
    tarima: 62,
    numeroItem: "NN236",
    descripcion: "Bathroom cabinet FA3-303091 FJQ12119",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 246,
    tarima: 62,
    numeroItem: "NN237",
    descripcion: "Bathroom cabinet FA-11-705225 color; SY7054",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 247,
    tarima: 62,
    numeroItem: "NN238",
    descripcion: "Bathroom cab FBOT-1",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 248,
    tarima: 63,
    numeroItem: "NN239",
    descripcion: "Bathroom cabinet F43303091 FSY7054",
    qty: 6,
    obs: "",
  },
  {
    numeroDigitado: 249,
    tarima: 63,
    numeroItem: "NN240",
    descripcion: "Bathroom cabinet F43-30309 FJQ12119",
    qty: 9,
    obs: "",
  },
  {
    numeroDigitado: 250,
    tarima: 64,
    numeroItem: "NN241",
    descripcion: "Cristal redondo baxcy sin ref 0.5m",
    qty: 17,
    obs: "",
  },
  {
    numeroDigitado: 251,
    tarima: 64,
    numeroItem: "NN242",
    descripcion: "Bathroom cabinet FP7H-45255",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 252,
    tarima: 64,
    numeroItem: "NN243",
    descripcion: "Bathroom cabinet FA2-501560 FJQ12119",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 253,
    tarima: 64,
    numeroItem: "NN244",
    descripcion: "Bathroom cabinet FA3-303091 FSY7054",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 254,
    tarima: 64,
    numeroItem: "NN245",
    descripcion: "Bathroom cabinet FBOT-1 FJQ12119",
    qty: 13,
    obs: "",
  },
  {
    numeroDigitado: 255,
    tarima: 64,
    numeroItem: "NN246",
    descripcion: "Bathroom cabinet FBOT-1 JQ18221",
    qty: 15,
    obs: "3 cajas de 5pcs",
  },
  {
    numeroDigitado: 256,
    tarima: 64,
    numeroItem: "NN247",
    descripcion: "Bathroom cab FA3-30309",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 257,
    tarima: 64,
    numeroItem: "NN248",
    descripcion: "Espejo con madera lateral",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 258,
    tarima: 65,
    numeroItem: "NN249",
    descripcion: "Caja gigante con piezas varias",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 259,
    tarima: 66,
    numeroItem: "NN250",
    descripcion: "Tarima con accesorios varios y tapas de inodoros varias",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 260,
    tarima: 67,
    numeroItem: "NN251",
    descripcion: "Espejo GY-5645 90x60",
    qty: 19,
    obs: "",
  },
  {
    numeroDigitado: 261,
    tarima: 67,
    numeroItem: "NN252",
    descripcion: "Espejo con marco 802-3 bueno",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 262,
    tarima: 67,
    numeroItem: "NN253",
    descripcion: "Jabonera de aluminio SD020",
    qty: 10,
    obs: "8 buenas mas 2 oxido",
  },
  {
    numeroDigitado: 263,
    tarima: 67,
    numeroItem: "NN254",
    descripcion: "Jabonera de aluminio A219-600",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 264,
    tarima: 67,
    numeroItem: "NN255",
    descripcion: "Jabonera de gancho",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 265,
    tarima: 67,
    numeroItem: "NN256",
    descripcion: "Piezas sin identificar ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 266,
    tarima: 68,
    numeroItem: "NN257",
    descripcion: "Lavamano CH2-ARM2W",
    qty: 17,
    obs: "",
  },
  {
    numeroDigitado: 267,
    tarima: 69,
    numeroItem: "NN258",
    descripcion: "Half side panel 531x1124",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 268,
    tarima: 69,
    numeroItem: "NN259",
    descripcion: "Removabled shelves 40719-B 864x282",
    qty: 12,
    obs: "2 cajas de 6pcs",
  },
  {
    numeroDigitado: 269,
    tarima: 69,
    numeroItem: "NN260",
    descripcion: "Fixed shelves 600x282 color; 40719-b",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 270,
    tarima: 69,
    numeroItem: "NN261",
    descripcion: "Trouser Shelves 600x500",
    qty: 12,
    obs: "2 cajas de 6sets",
  },
  {
    numeroDigitado: 271,
    tarima: 69,
    numeroItem: "NN262",
    descripcion: "Corner cabinet removable shelf",
    qty: 8,
    obs: "2 cajas de 4pcs",
  },
  {
    numeroDigitado: 272,
    tarima: 70,
    numeroItem: "NN263",
    descripcion: "Removable shelves 864x532 4071+-B",
    qty: 48,
    obs: "imperfectas; humedad",
  },
  {
    numeroDigitado: 273,
    tarima: 70,
    numeroItem: "NN264",
    descripcion: "Removable shelf 450x280",
    qty: 36,
    obs: "6 cajas de 6pcs, humedad",
  },
  {
    numeroDigitado: 274,
    tarima: 71,
    numeroItem: "NN265",
    descripcion: "Drawer 900x600 OB-6",
    qty: 8,
    obs: "2 cajas de 4set",
  },
  {
    numeroDigitado: 275,
    tarima: 71,
    numeroItem: "NN266",
    descripcion: "Producto sin identificar ",
    qty: 2,
    obs: "1 caja oak mas 1 caja negro",
  },
  {
    numeroDigitado: 276,
    tarima: 71,
    numeroItem: "NN267",
    descripcion: "Drawer 600x500",
    qty: 1,
    obs: "1 caja de 1 set",
  },
  {
    numeroDigitado: 277,
    tarima: 71,
    numeroItem: "NN268",
    descripcion: "Tie Storage 600x500 OB-1",
    qty: 4,
    obs: "1 caja de 4set",
  },
  {
    numeroDigitado: 278,
    tarima: 71,
    numeroItem: "NN269",
    descripcion: "Drawer 600x500",
    qty: 7,
    obs: "1 caja de 6set mas 1 caja de 1set",
  },
  {
    numeroDigitado: 279,
    tarima: 71,
    numeroItem: "NN270",
    descripcion: "Bathroom cab BFP7H-45",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 280,
    tarima: 71,
    numeroItem: "NN271",
    descripcion: "Bathroom cab FA3-303091",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 281,
    tarima: 71,
    numeroItem: "NN272",
    descripcion: "Bathroom cabinet 605x463x450 1918221",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 282,
    tarima: 71,
    numeroItem: "NN273",
    descripcion: "Trouser shelves 600x500",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 283,
    tarima: 71,
    numeroItem: "NN274",
    descripcion: "Lavamano 7821",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 284,
    tarima: 71,
    numeroItem: "NN275",
    descripcion: "Lavamano 7911",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 285,
    tarima: 72,
    numeroItem: "NN276",
    descripcion: "Lavamano 3004 white ",
    qty: 29,
    obs: "",
  },
  {
    numeroDigitado: 286,
    tarima: 40,
    numeroItem: "NN277",
    descripcion: "Lavamano 3002 white ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 287,
    tarima: 40,
    numeroItem: "NN278",
    descripcion: "Lavamano G-371",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 288,
    tarima: 40,
    numeroItem: "NN279",
    descripcion: "no existe",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 289,
    tarima: 73,
    numeroItem: "NN280",
    descripcion: "Llava ducha baxcy code; DEP163-2",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 290,
    tarima: 73,
    numeroItem: "NN281",
    descripcion: "Ducha baxcy code; BJC125-3",
    qty: 9,
    obs: "5 buenas mas 4 incompleta",
  },
  {
    numeroDigitado: 291,
    tarima: 73,
    numeroItem: "NN282",
    descripcion: "Ducha baxcy  two handle code; BJ120-4",
    qty: 4,
    obs: "2 completas mas 2 incompletas",
  },
  {
    numeroDigitado: 292,
    tarima: 73,
    numeroItem: "NN283",
    descripcion: "Ducha B252",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 293,
    tarima: 73,
    numeroItem: "NN284",
    descripcion: "Ducha B2H2A-F",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 294,
    tarima: 73,
    numeroItem: "NN285",
    descripcion: "Ducha Tw33281C",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 295,
    tarima: 73,
    numeroItem: "NN286",
    descripcion: "Ducha sin identificar ",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 296,
    tarima: 73,
    numeroItem: "NN287",
    descripcion: "Ducha sin identificar  N°2",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 297,
    tarima: 73,
    numeroItem: "NN288",
    descripcion: "Ducha 6AF",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 298,
    tarima: 73,
    numeroItem: "NN289",
    descripcion: "Ducha B2MH1A ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 299,
    tarima: 73,
    numeroItem: "NN290",
    descripcion: "Llave de fregadero B2MH-M1C",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 300,
    tarima: 73,
    numeroItem: "NN291",
    descripcion: "Llave de fregadero B2M-CL2S",
    qty: 1,
    obs: "incompleta",
  },
  {
    numeroDigitado: 301,
    tarima: 73,
    numeroItem: "NN292",
    descripcion: "Llave de fregadero B2L-10",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 302,
    tarima: 73,
    numeroItem: "NN293",
    descripcion: "Llave sin identificar ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 303,
    tarima: 73,
    numeroItem: "NN294",
    descripcion: "Mezcladora B252-1",
    qty: 1,
    obs: "imperfecta",
  },
  {
    numeroDigitado: 304,
    tarima: 73,
    numeroItem: "NN295",
    descripcion: "Mezcladora baxcy 11002F1",
    qty: 24,
    obs: "",
  },
  {
    numeroDigitado: 305,
    tarima: 73,
    numeroItem: "NN296",
    descripcion: "Llave de lavamano con delay BTD09-4",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 306,
    tarima: 73,
    numeroItem: "NN297",
    descripcion: "Llave de lavamano con delay sin ref",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 307,
    tarima: 73,
    numeroItem: "NN298",
    descripcion: "Mezcladora de fregadero B2MH-EX1C20031",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 308,
    tarima: 73,
    numeroItem: "NN299",
    descripcion: "Mezcladora de fregadero B2M-CL1C",
    qty: 10,
    obs: "8 completa mas 2 incompleta",
  },
  {
    numeroDigitado: 309,
    tarima: 73,
    numeroItem: "NN300",
    descripcion: "Piezas de; ducha, mezcladoras, varias",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 310,
    tarima: 74,
    numeroItem: "NN301",
    descripcion: "Base cabinet B2P-BWPC-90 oak (codigo cielos; 20057)",
    qty: 5,
    obs: "cajas selladas",
  },
  {
    numeroDigitado: 311,
    tarima: 74,
    numeroItem: "NN302",
    descripcion: "Base cabinet w/drawer (20082) B4GO-BWPC-45",
    qty: 6,
    obs: "cajas selladas",
  },
  {
    numeroDigitado: 312,
    tarima: 74,
    numeroItem: "NN303",
    descripcion: "Bathroom cabinet FA3-303091 FSY7054",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 313,
    tarima: 75,
    numeroItem: "NN304",
    descripcion: "Accesorio de closet F26-900",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 314,
    tarima: 75,
    numeroItem: "NN305",
    descripcion: "Accesorio de closet F24A",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 315,
    tarima: 75,
    numeroItem: "NN306",
    descripcion: "Accesorio de closet F13",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 316,
    tarima: 75,
    numeroItem: "NN307",
    descripcion: "Lavamano 5012",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 317,
    tarima: 75,
    numeroItem: "NN308",
    descripcion: "Mueble 7027 860x380x440",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 318,
    tarima: 75,
    numeroItem: "NN309",
    descripcion: "Mueble de cristal 88x33x43 dice a manuscrito;GY-40 ",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 319,
    tarima: 75,
    numeroItem: "NN310",
    descripcion: "Maletin de baño BY-856 845x445x180",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 320,
    tarima: 76,
    numeroItem: "NN311",
    descripcion: "Jabonera YS-2Y69",
    qty: 7,
    obs: "",
  },
  {
    numeroDigitado: 321,
    tarima: 76,
    numeroItem: "NN312",
    descripcion: "Jabonera YS-6669",
    qty: 7,
    obs: "",
  },
  {
    numeroDigitado: 322,
    tarima: 76,
    numeroItem: "NN313",
    descripcion: "Toallera YS3510",
    qty: 7,
    obs: "",
  },
  {
    numeroDigitado: 323,
    tarima: 76,
    numeroItem: "NN314",
    descripcion: "Jabonerea YS-6585A",
    qty: 9,
    obs: "",
  },
  {
    numeroDigitado: 324,
    tarima: 76,
    numeroItem: "NN315",
    descripcion: "Jabonera YS-2684",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 325,
    tarima: 76,
    numeroItem: "NN316",
    descripcion: "Jabonera YS-9169",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 326,
    tarima: 76,
    numeroItem: "NN317",
    descripcion: "Jabonera XS-1069",
    qty: 8,
    obs: "",
  },
  {
    numeroDigitado: 327,
    tarima: 76,
    numeroItem: "NN318",
    descripcion: "Jabonera Y52669",
    qty: 8,
    obs: "",
  },
  {
    numeroDigitado: 328,
    tarima: 76,
    numeroItem: "NN319",
    descripcion: "Accesorio de baño YS-BB13",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 329,
    tarima: 76,
    numeroItem: "NN320",
    descripcion: "Accesorio de baño YS-6688",
    qty: 10,
    obs: "",
  },
  {
    numeroDigitado: 330,
    tarima: 76,
    numeroItem: "NN321",
    descripcion: "Accesorio de baño sin ref",
    qty: 18,
    obs: "",
  },
  {
    numeroDigitado: 331,
    tarima: 76,
    numeroItem: "NN322",
    descripcion: "Accesorio de baño sin ref",
    qty: 7,
    obs: "",
  },
  {
    numeroDigitado: 332,
    tarima: 76,
    numeroItem: "NN323",
    descripcion: "Accesorio de baño sin ref",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 333,
    tarima: 76,
    numeroItem: "NN324",
    descripcion: "Accesorio de baño sin ref",
    qty: 13,
    obs: "",
  },
  {
    numeroDigitado: 334,
    tarima: 76,
    numeroItem: "NN325",
    descripcion: "Accesorio de baño sin ref",
    qty: 9,
    obs: "",
  },
  {
    numeroDigitado: 335,
    tarima: 76,
    numeroItem: "NN326",
    descripcion: "Toallera sin ref",
    qty: 8,
    obs: "",
  },
  {
    numeroDigitado: 336,
    tarima: 76,
    numeroItem: "NN327",
    descripcion: "Ducha LEMP-2P",
    qty: 11,
    obs: "",
  },
  {
    numeroDigitado: 337,
    tarima: 76,
    numeroItem: "NN328",
    descripcion: "Accesorio de baño YS26003",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 338,
    tarima: 76,
    numeroItem: "NN329",
    descripcion: "Set de accesorio de baño YS5300-3",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 339,
    tarima: 76,
    numeroItem: "NN330",
    descripcion: "Set de accesorio de baño 2400-3",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 340,
    tarima: 76,
    numeroItem: "NN331",
    descripcion: "Set de accesorio de baño YS-30003",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 341,
    tarima: 76,
    numeroItem: "NN332",
    descripcion: "Set de accesorio de baño YS-1100-3",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 342,
    tarima: 76,
    numeroItem: "NN333",
    descripcion: "Set de accesorio de baño YS-5900-3",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 343,
    tarima: 76,
    numeroItem: "NN334",
    descripcion: "Pieza desconocida ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 344,
    tarima: 77,
    numeroItem: "NN335",
    descripcion: "Mezcladora para fregadero B2L-10C",
    qty: 78,
    obs: "",
  },
  {
    numeroDigitado: 345,
    tarima: 77,
    numeroItem: "NN336",
    descripcion: "Mueble con espejo negro BY-861",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 346,
    tarima: 78,
    numeroItem: "NN337",
    descripcion: "Desague code; C11011",
    qty: 197,
    obs: "",
  },
  {
    numeroDigitado: 347,
    tarima: 78,
    numeroItem: "NN338",
    descripcion: "Lavamano 7657",
    qty: 7,
    obs: "",
  },
  {
    numeroDigitado: 348,
    tarima: 78,
    numeroItem: "NN339",
    descripcion: "Lavamano 7907",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 349,
    tarima: 78,
    numeroItem: "NN340",
    descripcion: "Lavamano de cristal redondo ref; CBA1006-1",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 350,
    tarima: 78,
    numeroItem: "NN341",
    descripcion: "Lavamano de cristal redondo ref; GY-17",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 351,
    tarima: 78,
    numeroItem: "NN342",
    descripcion: "Lavamano ref; 7029E cuadrado",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 352,
    tarima: 78,
    numeroItem: "NN343",
    descripcion: "Lavamano de cristal CBA84001-1",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 353,
    tarima: 78,
    numeroItem: "NN344",
    descripcion: "Lavamano CBA85056",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 354,
    tarima: 78,
    numeroItem: "NN345",
    descripcion: "Lavamano de piedra blanca NP-A50-LW",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 355,
    tarima: 78,
    numeroItem: "NN346",
    descripcion: "Tanque de inodoro A0616",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 356,
    tarima: 79,
    numeroItem: "NN347",
    descripcion: "Lavamano 7098",
    qty: 40,
    obs: "",
  },
  {
    numeroDigitado: 357,
    tarima: 79,
    numeroItem: "NN348",
    descripcion: "Ganinete negro 955x35x35 ref; 868-4",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 358,
    tarima: 80,
    numeroItem: "NN349",
    descripcion: "Espejo negro BY-861",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 359,
    tarima: 80,
    numeroItem: "NN350",
    descripcion: "Inodoro A0622",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 360,
    tarima: 80,
    numeroItem: "NN351",
    descripcion: "Gabinete BY-856 845x445x180 oak",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 361,
    tarima: 80,
    numeroItem: "NN352",
    descripcion: "Gabinete oak BY803 con espejo (20053) (1240x540x190)",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 362,
    tarima: 80,
    numeroItem: "NN353",
    descripcion: "Gabinete negro BY-868BL 950x345x355",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 363,
    tarima: 80,
    numeroItem: "NN354",
    descripcion: "Gabinete 868-4 negro ",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 364,
    tarima: 81,
    numeroItem: "NN355",
    descripcion: "Piezas de baño varia",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 365,
    tarima: 82,
    numeroItem: "NN356",
    descripcion: "Set de accesorios de baño ALV006-K3P",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 366,
    tarima: 82,
    numeroItem: "NN357",
    descripcion: "Set de accesorios de baño ALB-02K3P",
    qty: 7,
    obs: "incompleta",
  },
  {
    numeroDigitado: 367,
    tarima: 82,
    numeroItem: "NN358",
    descripcion: "Set de accesorios de baño",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 368,
    tarima: 82,
    numeroItem: "NN359",
    descripcion: "Set de accesorios de baño sin ref",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 369,
    tarima: 82,
    numeroItem: "NN360",
    descripcion: "Accesorios de baño EV005-06",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 370,
    tarima: 82,
    numeroItem: "NN361",
    descripcion: "Pieza no identificada ref; CFF8HZ-8",
    qty: 123,
    obs: "",
  },
  {
    numeroDigitado: 371,
    tarima: 82,
    numeroItem: "NN362",
    descripcion: "Mangueras de ducha sin ref",
    qty: 61,
    obs: "",
  },
  {
    numeroDigitado: 372,
    tarima: 82,
    numeroItem: "NN363",
    descripcion: "Pieza no identificada sin ref",
    qty: 108,
    obs: "",
  },
  {
    numeroDigitado: 373,
    tarima: 82,
    numeroItem: "NN364",
    descripcion: "Baso de baño de cristaldoble con base aluminio ref; 20210",
    qty: 15,
    obs: "",
  },
  {
    numeroDigitado: 374,
    tarima: 82,
    numeroItem: "NN365",
    descripcion:
      "Escobilla de baño con base de aluminio y vaso de cristal ref; EV-002-11",
    qty: 5,
    obs: "4 mas 1 incompleta",
  },
  {
    numeroDigitado: 375,
    tarima: 82,
    numeroItem: "NN366",
    descripcion: "Vaso de cristal de baño con base aluminio Ref; EV002-09",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 376,
    tarima: 82,
    numeroItem: "NN367",
    descripcion: "Vaso de cristal con base aluminio ref; ALV0601",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 377,
    tarima: 82,
    numeroItem: "NN368",
    descripcion: "Plato para jabonera con vase aluminio sin ref",
    qty: 6,
    obs: "",
  },
  {
    numeroDigitado: 378,
    tarima: 82,
    numeroItem: "NN369",
    descripcion: "Vaso de cristal con base tipo gancho sin ref",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 379,
    tarima: 82,
    numeroItem: "NN370",
    descripcion: "Dispensador de papel de baño sin ref",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 380,
    tarima: 82,
    numeroItem: "NN371",
    descripcion:
      "Dispensador de papel higienico tipo L aluminio mirror sin ref",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 381,
    tarima: 82,
    numeroItem: "NN372",
    descripcion: "Dispensador de papel higienico sin ref",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 382,
    tarima: 82,
    numeroItem: "NN373",
    descripcion: "Dispensador de papel higienico con cubierta sin ref",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 383,
    tarima: 82,
    numeroItem: "NN374",
    descripcion: "Escobilla de baño con estuche movil ",
    qty: 1,
    obs: "incompleta",
  },
  {
    numeroDigitado: 384,
    tarima: 83,
    numeroItem: "NN375",
    descripcion: "Lavamano CH2-ARM2W",
    qty: 21,
    obs: "",
  },
  {
    numeroDigitado: 385,
    tarima: 84,
    numeroItem: "NN376",
    descripcion: "Mueble negro BY-803",
    qty: 2,
    obs: "surfato en tornillos",
  },
  {
    numeroDigitado: 386,
    tarima: 84,
    numeroItem: "NN377",
    descripcion: "Tapa de inodoro 071 cover plate",
    qty: 48,
    obs: "nuevas",
  },
  {
    numeroDigitado: 387,
    tarima: 84,
    numeroItem: "NN378",
    descripcion: "Tapa de inodoro variadas",
    qty: 19,
    obs: "variadas no optima",
  },
  {
    numeroDigitado: 388,
    tarima: 85,
    numeroItem: "NN379",
    descripcion: "Mueble 7021 60-m brown",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 389,
    tarima: 85,
    numeroItem: "NN380",
    descripcion: "Mueble 7021 60-m black",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 390,
    tarima: 85,
    numeroItem: "NN381",
    descripcion: "Mangueras flex sin ref",
    qty: 31,
    obs: "",
  },
  {
    numeroDigitado: 391,
    tarima: 85,
    numeroItem: "NN382",
    descripcion: "Tapa de inodoro nueva varias",
    qty: 12,
    obs: "",
  },
  {
    numeroDigitado: 392,
    tarima: 85,
    numeroItem: "NN383",
    descripcion: "Tapa de inodoro variadas",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 393,
    tarima: 86,
    numeroItem: "NN384",
    descripcion: "Toilet A0622 720x430x710",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 394,
    tarima: 86,
    numeroItem: "NN385",
    descripcion: "Toilet sin ref",
    qty: 1,
    obs: "sin tapa",
  },
  {
    numeroDigitado: 395,
    tarima: 86,
    numeroItem: "NN386",
    descripcion: "Pcs de duchas varias",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 396,
    tarima: 86,
    numeroItem: "NN387",
    descripcion: "Pcs de baños para toallas varia",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 397,
    tarima: 86,
    numeroItem: "NN388",
    descripcion: "Mobiliario  ref B2P-BWPC-120",
    qty: 4,
    obs: "humedad",
  },
  {
    numeroDigitado: 398,
    tarima: 86,
    numeroItem: "NN389",
    descripcion: "Mobiliario B1PE-BWPC-109",
    qty: 2,
    obs: "humedad",
  },
  {
    numeroDigitado: 399,
    tarima: 86,
    numeroItem: "NN390",
    descripcion: "Mobiliario B2P-BWPC-90",
    qty: 1,
    obs: "humedad",
  },
  {
    numeroDigitado: 400,
    tarima: 88,
    numeroItem: "NN391",
    descripcion: "Mobiliario blanco B2PBWPC-90",
    qty: 10,
    obs: "humedad",
  },
  {
    numeroDigitado: 401,
    tarima: 88,
    numeroItem: "NN392",
    descripcion: "Mobiliario blanco B1PEBWPC-109",
    qty: 4,
    obs: "humedad",
  },
  {
    numeroDigitado: 402,
    tarima: 88,
    numeroItem: "NN393",
    descripcion: "B2P BWPC120 blanco",
    qty: 1,
    obs: "humedad",
  },
  {
    numeroDigitado: 403,
    tarima: 89,
    numeroItem: "NN394",
    descripcion: "Mobiliario B1PE-BWPC-109",
    qty: 4,
    obs: "humedad",
  },
  {
    numeroDigitado: 404,
    tarima: 89,
    numeroItem: "NN395",
    descripcion: "Mobiliario B2P-BWPC",
    qty: 3,
    obs: "humedad",
  },
  {
    numeroDigitado: 405,
    tarima: 89,
    numeroItem: "NN458",
    descripcion: "Lavamano sin ref, con pedestal",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 406,
    tarima: 90,
    numeroItem: "NN396",
    descripcion: "Lavamano R7549",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 407,
    tarima: 90,
    numeroItem: "NN397",
    descripcion: "Lavamano 7029E",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 408,
    tarima: 90,
    numeroItem: "NN398",
    descripcion: "Lavamano OK0841",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 409,
    tarima: 90,
    numeroItem: "NN399",
    descripcion: "Lavamano OK1128",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 410,
    tarima: 90,
    numeroItem: "NN400",
    descripcion: "no existe",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 411,
    tarima: 90,
    numeroItem: "NN401",
    descripcion: "Lavamano con forma de concha sin ref",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 412,
    tarima: 90,
    numeroItem: "NN402",
    descripcion: "Lavamano Charns-5010",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 413,
    tarima: 90,
    numeroItem: "NN403",
    descripcion: "Lavamano OK1159B",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 414,
    tarima: 90,
    numeroItem: "NN405",
    descripcion: "Lavamano CHNS-4009 crema",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 415,
    tarima: 91,
    numeroItem: "NN404",
    descripcion: "Lavamano P7533 rectangular",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 416,
    tarima: 91,
    numeroItem: "NN405",
    descripcion: "Lavamano CHNS-4009 crema",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 417,
    tarima: 91,
    numeroItem: "NN406",
    descripcion: "Lavamano rectangular 0.61x0.45",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 418,
    tarima: 91,
    numeroItem: "NN407",
    descripcion: "Lavamano OK-1128",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 419,
    tarima: 91,
    numeroItem: "NN408",
    descripcion: "Lavamano ok-0388",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 420,
    tarima: 91,
    numeroItem: "NN409",
    descripcion: "Lavamano CH-5004W",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 421,
    tarima: 91,
    numeroItem: "NN410",
    descripcion: "Lavamano sin ref",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 422,
    tarima: 91,
    numeroItem: "NN411",
    descripcion: "Lavamano OK0897",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 423,
    tarima: 91,
    numeroItem: "NN412",
    descripcion: "Lavamano OK0477",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 424,
    tarima: 91,
    numeroItem: "NN413",
    descripcion: "Lavamano CH4009",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 425,
    tarima: 91,
    numeroItem: "NN414",
    descripcion: "Lavamano OK1539",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 426,
    tarima: 91,
    numeroItem: "NN415",
    descripcion: "Lavamano P918",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 427,
    tarima: 92,
    numeroItem: "NN416",
    descripcion: "Lavamano 2H-5003W",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 428,
    tarima: 92,
    numeroItem: "NN417",
    descripcion: "Lavamano de cristal redondo CBA85050",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 429,
    tarima: 92,
    numeroItem: "NN418",
    descripcion: "Lavamano rojo 0.30 de cristal",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 430,
    tarima: 92,
    numeroItem: "NN419",
    descripcion: "Lavamano OK0413",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 431,
    tarima: 92,
    numeroItem: "NN420",
    descripcion: "Lavamano OK0413",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 432,
    tarima: 92,
    numeroItem: "NN421",
    descripcion: "Lavamano AC217",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 433,
    tarima: 92,
    numeroItem: "NN422",
    descripcion: "Lavamano BY-803L ",
    qty: 2,
    obs: "imperfectos; humedad, manchas",
  },
  {
    numeroDigitado: 434,
    tarima: 92,
    numeroItem: "NN423",
    descripcion: "Lavamano OK0419",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 435,
    tarima: 92,
    numeroItem: "NN424",
    descripcion: "Lavamano de cristal cuadrado 0.42x0.42",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 436,
    tarima: 92,
    numeroItem: "NN425",
    descripcion: "Lavamano OK-0408",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 437,
    tarima: 93,
    numeroItem: "NN426",
    descripcion: "Bathroom cabinet 1000x520x430 SY7007",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 438,
    tarima: 93,
    numeroItem: "NN427",
    descripcion: "Bathroom cabinet 1000x520x420 JQ18221",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 439,
    tarima: 93,
    numeroItem: "NN428",
    descripcion: "Bathroom cabinet FBOT-2-801540 JQ18221",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 440,
    tarima: 93,
    numeroItem: "NN429",
    descripcion: "Bathroom cabinet FBOT-2 801540 FJQ12119",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 441,
    tarima: 93,
    numeroItem: "NN430",
    descripcion: "Bathoom cabinet FA2-501560 JQ18221",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 442,
    tarima: 93,
    numeroItem: "NN431",
    descripcion: "Pieza no identificada ref; W0-15",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 443,
    tarima: 93,
    numeroItem: "NN432",
    descripcion: "Bathroom cabinet JQ18221 FM34",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 444,
    tarima: 93,
    numeroItem: "NN433",
    descripcion: "Bathroom cabinet FMH-53850",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 445,
    tarima: 93,
    numeroItem: "NN434",
    descripcion: "Bathroom cabinet FA3-303091 SY7052",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 446,
    tarima: 93,
    numeroItem: "NN435",
    descripcion: "Bathroom cabinet FM3H-79350",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 447,
    tarima: 93,
    numeroItem: "NN438",
    descripcion: "Accesorio de closet F12",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 448,
    tarima: 93,
    numeroItem: "NN439",
    descripcion: "Accesorio de close sin referencia",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 449,
    tarima: 93,
    numeroItem: "NN440",
    descripcion: "Mezcladora de fregadero B2L-10C",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 450,
    tarima: 93,
    numeroItem: "NN441",
    descripcion: "Mezcladora de fregadero B2-CL1C (codigo cielos; 20073)",
    qty: 0,
    obs: "",
  },
  {
    numeroDigitado: 451,
    tarima: 93,
    numeroItem: "NN442",
    descripcion: "Accesorio de close sin ref 0.46m",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 452,
    tarima: 93,
    numeroItem: "NN443",
    descripcion: "Accesorio de close con espejo 1.22x0.32 sin ref",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 453,
    tarima: 93,
    numeroItem: "NN443b",
    descripcion: "Pieza no identificada sin ref ",
    qty: 1,
    obs: "antigüedad",
  },
  {
    numeroDigitado: 454,
    tarima: 94,
    numeroItem: "NN444",
    descripcion: "Tanque A0616",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 455,
    tarima: 94,
    numeroItem: "NN445",
    descripcion: "Inodoro A0616 (700x400x520)",
    qty: 6,
    obs: "uno de ellos al parecer estaba en exhibicion",
  },
  {
    numeroDigitado: 456,
    tarima: 95,
    numeroItem: "NN446",
    descripcion: "Bathroom cabinet JQ18221 ",
    qty: 6,
    obs: "",
  },
  {
    numeroDigitado: 457,
    tarima: 95,
    numeroItem: "NN447",
    descripcion: "Bathroom cabinet EM1-6080 JQ12119",
    qty: 15,
    obs: "3 cajas de 5 pcs",
  },
  {
    numeroDigitado: 458,
    tarima: 95,
    numeroItem: "NN448",
    descripcion: "Inodoro A0622",
    qty: 3,
    obs: "2 bueno mas 1 roto",
  },
  {
    numeroDigitado: 459,
    tarima: 96,
    numeroItem: "NN449",
    descripcion: "Tanque de inodoro sin ref",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 460,
    tarima: 96,
    numeroItem: "NN450",
    descripcion: "Inodoro sin ref",
    qty: 1,
    obs: "imperfecto; grieta y sin tapa",
  },
  {
    numeroDigitado: 461,
    tarima: 96,
    numeroItem: "NN451",
    descripcion: "Inodoro A0601-1",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 462,
    tarima: 96,
    numeroItem: "NN452",
    descripcion: "Inodoro sin ref",
    qty: 1,
    obs: "sin tapa, fuera de su caja",
  },
  {
    numeroDigitado: 463,
    tarima: 97,
    numeroItem: "NN453",
    descripcion: "Lavamano 7953",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 464,
    tarima: 97,
    numeroItem: "NN454",
    descripcion: "Inodoro A0601",
    qty: 3,
    obs: "",
  },
  {
    numeroDigitado: 465,
    tarima: 97,
    numeroItem: "NN455",
    descripcion: "Inodoro A0616",
    qty: 2,
    obs: "",
  },
  {
    numeroDigitado: 466,
    tarima: 98,
    numeroItem: "NN456",
    descripcion: "Inodoro A0622",
    qty: 5,
    obs: "",
  },
  {
    numeroDigitado: 467,
    tarima: 99,
    numeroItem: "NN457",
    descripcion: "Inodoro A0631",
    qty: 6,
    obs: "",
  },
  {
    numeroDigitado: 468,
    tarima: 100,
    numeroItem: "NN458",
    descripcion: "Inodoro A0622",
    qty: 12,
    obs: "",
  },
  {
    numeroDigitado: 469,
    tarima: 100,
    numeroItem: "NN467",
    descripcion: "Mueble 7027 maple(L14)",
    qty: 1,
    obs: "caja destapada, talvez incompleto",
  },
  {
    numeroDigitado: 470,
    tarima: 101,
    numeroItem: "NN459",
    descripcion: "Lavamano 5003",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 471,
    tarima: 101,
    numeroItem: "NN460",
    descripcion: "Lavamano ref manuscrito; 7533",
    qty: 4,
    obs: "",
  },
  {
    numeroDigitado: 472,
    tarima: 101,
    numeroItem: "NN461",
    descripcion: "Lavamano ref; 7821",
    qty: 1,
    obs: "incompleto",
  },
  {
    numeroDigitado: 473,
    tarima: 101,
    numeroItem: "NN462",
    descripcion: "Lavamano ref; manuscrito; CH2-AFG1W",
    qty: 1,
    obs: "",
  },
  {
    numeroDigitado: 474,
    tarima: 101,
    numeroItem: "NN463",
    descripcion: "Pieza no identificada ref; TR-270A",
    qty: 9,
    obs: "",
  },
];
